
// This file has been generated by the GUI designer. Do not modify.
namespace BuildingFormulas
{
	public partial class dlgDisplayStoredData
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Table tblDataStore;
		
		private global::Gtk.Label lblDepth;
		
		private global::Gtk.Label lblDepthFeet;
		
		private global::Gtk.Label lblDepthInches;
		
		private global::Gtk.Label lblDepthYards;
		
		private global::Gtk.Label lblFeet;
		
		private global::Gtk.Label lblInches;
		
		private global::Gtk.Label lblLength;
		
		private global::Gtk.Label lblLengthFeet;
		
		private global::Gtk.Label lblLengthInches;
		
		private global::Gtk.Label lblLengthYards;
		
		private global::Gtk.Label lblWidth;
		
		private global::Gtk.Label lblWidthFeet;
		
		private global::Gtk.Label lblWidthInches;
		
		private global::Gtk.Label lblWidthYards;
		
		private global::Gtk.Label lblYards;
		
		private global::Gtk.Label lblRecPos;
		
		private global::Gtk.Button button199;
		
		private global::Gtk.Button button198;
		
		private global::Gtk.Button button197;
		
		private global::Gtk.Button button196;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BuildingFormulas.dlgDisplayStoredData
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "BuildingFormulas.dlgDisplayStoredData";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(8));
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			// Internal child BuildingFormulas.dlgDisplayStoredData.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tblDataStore = new global::Gtk.Table (((uint)(4)), ((uint)(4)), false);
			this.tblDataStore.WidthRequest = 670;
			this.tblDataStore.HeightRequest = 186;
			this.tblDataStore.Name = "tblDataStore";
			this.tblDataStore.RowSpacing = ((uint)(6));
			this.tblDataStore.ColumnSpacing = ((uint)(6));
			this.tblDataStore.BorderWidth = ((uint)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblDepth = new global::Gtk.Label ();
			this.lblDepth.WidthRequest = 142;
			this.lblDepth.HeightRequest = 30;
			this.lblDepth.Name = "lblDepth";
			this.lblDepth.LabelProp = global::Mono.Unix.Catalog.GetString ("Depth:");
			this.tblDataStore.Add (this.lblDepth);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblDepth]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblDepthFeet = new global::Gtk.Label ();
			this.lblDepthFeet.WidthRequest = 159;
			this.lblDepthFeet.HeightRequest = 30;
			this.lblDepthFeet.Name = "lblDepthFeet";
			this.lblDepthFeet.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
			this.tblDataStore.Add (this.lblDepthFeet);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblDepthFeet]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblDepthInches = new global::Gtk.Label ();
			this.lblDepthInches.WidthRequest = 159;
			this.lblDepthInches.HeightRequest = 30;
			this.lblDepthInches.Name = "lblDepthInches";
			this.lblDepthInches.LabelProp = global::Mono.Unix.Catalog.GetString ("label9");
			this.tblDataStore.Add (this.lblDepthInches);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblDepthInches]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(3));
			w4.RightAttach = ((uint)(4));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblDepthYards = new global::Gtk.Label ();
			this.lblDepthYards.WidthRequest = 159;
			this.lblDepthYards.HeightRequest = 30;
			this.lblDepthYards.Name = "lblDepthYards";
			this.lblDepthYards.LabelProp = global::Mono.Unix.Catalog.GetString ("label7");
			this.tblDataStore.Add (this.lblDepthYards);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblDepthYards]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblFeet = new global::Gtk.Label ();
			this.lblFeet.WidthRequest = 159;
			this.lblFeet.HeightRequest = 24;
			this.lblFeet.Name = "lblFeet";
			this.lblFeet.LabelProp = global::Mono.Unix.Catalog.GetString ("Feet");
			this.tblDataStore.Add (this.lblFeet);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblFeet]));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblInches = new global::Gtk.Label ();
			this.lblInches.WidthRequest = 159;
			this.lblInches.HeightRequest = 24;
			this.lblInches.Name = "lblInches";
			this.lblInches.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.tblDataStore.Add (this.lblInches);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblInches]));
			w7.LeftAttach = ((uint)(3));
			w7.RightAttach = ((uint)(4));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblLength = new global::Gtk.Label ();
			this.lblLength.WidthRequest = 142;
			this.lblLength.HeightRequest = 30;
			this.lblLength.Name = "lblLength";
			this.lblLength.LabelProp = global::Mono.Unix.Catalog.GetString ("Length:");
			this.tblDataStore.Add (this.lblLength);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblLength]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblLengthFeet = new global::Gtk.Label ();
			this.lblLengthFeet.WidthRequest = 159;
			this.lblLengthFeet.HeightRequest = 30;
			this.lblLengthFeet.Name = "lblLengthFeet";
			this.lblLengthFeet.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
			this.tblDataStore.Add (this.lblLengthFeet);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblLengthFeet]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblLengthInches = new global::Gtk.Label ();
			this.lblLengthInches.WidthRequest = 159;
			this.lblLengthInches.HeightRequest = 30;
			this.lblLengthInches.Name = "lblLengthInches";
			this.lblLengthInches.LabelProp = global::Mono.Unix.Catalog.GetString ("label9");
			this.tblDataStore.Add (this.lblLengthInches);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblLengthInches]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.LeftAttach = ((uint)(3));
			w10.RightAttach = ((uint)(4));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblLengthYards = new global::Gtk.Label ();
			this.lblLengthYards.WidthRequest = 159;
			this.lblLengthYards.HeightRequest = 30;
			this.lblLengthYards.Name = "lblLengthYards";
			this.lblLengthYards.LabelProp = global::Mono.Unix.Catalog.GetString ("label7");
			this.tblDataStore.Add (this.lblLengthYards);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblLengthYards]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblWidth = new global::Gtk.Label ();
			this.lblWidth.WidthRequest = 142;
			this.lblWidth.HeightRequest = 30;
			this.lblWidth.Name = "lblWidth";
			this.lblWidth.LabelProp = global::Mono.Unix.Catalog.GetString ("Width:");
			this.tblDataStore.Add (this.lblWidth);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblWidth]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblWidthFeet = new global::Gtk.Label ();
			this.lblWidthFeet.WidthRequest = 159;
			this.lblWidthFeet.HeightRequest = 30;
			this.lblWidthFeet.Name = "lblWidthFeet";
			this.lblWidthFeet.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
			this.tblDataStore.Add (this.lblWidthFeet);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblWidthFeet]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.LeftAttach = ((uint)(2));
			w13.RightAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblWidthInches = new global::Gtk.Label ();
			this.lblWidthInches.WidthRequest = 159;
			this.lblWidthInches.HeightRequest = 30;
			this.lblWidthInches.Name = "lblWidthInches";
			this.lblWidthInches.LabelProp = global::Mono.Unix.Catalog.GetString ("label9");
			this.tblDataStore.Add (this.lblWidthInches);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblWidthInches]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.LeftAttach = ((uint)(3));
			w14.RightAttach = ((uint)(4));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblWidthYards = new global::Gtk.Label ();
			this.lblWidthYards.WidthRequest = 159;
			this.lblWidthYards.HeightRequest = 30;
			this.lblWidthYards.Name = "lblWidthYards";
			this.lblWidthYards.LabelProp = global::Mono.Unix.Catalog.GetString ("label7");
			this.tblDataStore.Add (this.lblWidthYards);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblWidthYards]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblDataStore.Gtk.Table+TableChild
			this.lblYards = new global::Gtk.Label ();
			this.lblYards.WidthRequest = 159;
			this.lblYards.HeightRequest = 24;
			this.lblYards.Name = "lblYards";
			this.lblYards.LabelProp = global::Mono.Unix.Catalog.GetString ("Yards");
			this.tblDataStore.Add (this.lblYards);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tblDataStore [this.lblYards]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox1.Add (this.tblDataStore);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tblDataStore]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblRecPos = new global::Gtk.Label ();
			this.lblRecPos.Name = "lblRecPos";
			this.lblRecPos.LabelProp = global::Mono.Unix.Catalog.GetString ("label11");
			this.vbox2.Add (this.lblRecPos);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblRecPos]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w20.Position = 0;
			// Internal child BuildingFormulas.dlgDisplayStoredData.ActionArea
			global::Gtk.HButtonBox w21 = this.ActionArea;
			w21.Name = "dialog1_ActionArea";
			w21.Spacing = 10;
			w21.BorderWidth = ((uint)(5));
			w21.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button199 = new global::Gtk.Button ();
			this.button199.CanFocus = true;
			this.button199.Name = "button199";
			this.button199.UseUnderline = true;
			this.button199.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.AddActionWidget (this.button199, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w21 [this.button199]));
			w22.Expand = false;
			w22.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button198 = new global::Gtk.Button ();
			this.button198.CanFocus = true;
			this.button198.Name = "button198";
			this.button198.UseUnderline = true;
			this.button198.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.AddActionWidget (this.button198, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w21 [this.button198]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button197 = new global::Gtk.Button ();
			this.button197.CanFocus = true;
			this.button197.Name = "button197";
			this.button197.UseUnderline = true;
			this.button197.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.AddActionWidget (this.button197, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w24 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w21 [this.button197]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button196 = new global::Gtk.Button ();
			this.button196.CanFocus = true;
			this.button196.Name = "button196";
			this.button196.UseUnderline = true;
			this.button196.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.AddActionWidget (this.button196, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w21 [this.button196]));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w21 [this.buttonCancel]));
			w26.Position = 4;
			w26.Expand = false;
			w26.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w21 [this.buttonOk]));
			w27.Position = 5;
			w27.Expand = false;
			w27.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
