
// This file has been generated by the GUI designer. Do not modify.
namespace BuildingFormulas
{
	public partial class RightHexagonalPyramidVolume : Gtk.Window
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget BuildingFormulas.Right hexagonal pyramid
			this.Name = "BuildingFormulas.Right hexagonal pyramid";
			this.Title = global::Mono.Unix.Catalog.GetString("Right hexagonal pyramid");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
