
// This file has been generated by the GUI designer. Do not modify.
namespace BuildingFormulas
{
	public partial class SquareRectangleSurfaceArea
	{
		private global::Gtk.VBox dialog1_VBox;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.Table tblData;
		
		private global::Gtk.Label lblEmpty;
		
		private global::Gtk.Label lblFeet;
		
		private global::Gtk.Label lblInches;
		
		private global::Gtk.Label lblLength;
		
		private global::Gtk.Label lblWidth;
		
		private global::Gtk.Label lblYards;
		
		private global::Gtk.Entry txtLengthFeet;
		
		private global::Gtk.Entry txtLengthInches;
		
		private global::Gtk.Entry txtLengthYard;
		
		private global::Gtk.Entry txtWidthFeet;
		
		private global::Gtk.Entry txtWidthInches;
		
		private global::Gtk.Entry txtWidthYard;
		
		private global::Gtk.Alignment alignment2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Alignment alignment4;
		
		private global::Gtk.Table tblCubicTotals;
		
		private global::Gtk.Alignment alignment11;
		
		private global::Gtk.Alignment alignment12;
		
		private global::Gtk.Label lblSurfaceFeet;
		
		private global::Gtk.Label lblSurfaceInches;
		
		private global::Gtk.Label lblSurfaceYards;
		
		private global::Gtk.Entry txtSurfaceFeet;
		
		private global::Gtk.Entry txtSurfaceInches;
		
		private global::Gtk.Entry txtSurfaceYards;
		
		private global::Gtk.Alignment alignment3;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Alignment alignment5;
		
		private global::Gtk.VButtonBox vbtnLeft;
		
		private global::Gtk.Button btnClear;
		
		private global::Gtk.Button btnStandard;
		
		private global::Gtk.Button btnMetric;
		
		private global::Gtk.Alignment alignment6;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Alignment alignment7;
		
		private global::Gtk.VButtonBox vbtnCenter;
		
		private global::Gtk.Button btnSolve;
		
		private global::Gtk.Button btnStore;
		
		private global::Gtk.Button btnDisplayStore;
		
		private global::Gtk.Button btnClearStore;
		
		private global::Gtk.Alignment alignment8;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Alignment alignment9;
		
		private global::Gtk.VButtonBox vbtnRight;
		
		private global::Gtk.Button btnPrintForm;
		
		private global::Gtk.Button btnPrintStored;
		
		private global::Gtk.Button btnSaveForm;
		
		private global::Gtk.Button btnClose;
		
		private global::Gtk.Alignment alignment10;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BuildingFormulas.SquareRectangleSurfaceArea
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "BuildingFormulas.SquareRectangleSurfaceArea";
			this.Title = global::Mono.Unix.Catalog.GetString ("SquareRectangleSurfaceAreaFormula");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(8));
			// Container child BuildingFormulas.SquareRectangleSurfaceArea.Gtk.Container+ContainerChild
			this.dialog1_VBox = new global::Gtk.VBox ();
			this.dialog1_VBox.Name = "dialog1_VBox";
			this.dialog1_VBox.BorderWidth = ((uint)(6));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tblData = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.tblData.WidthRequest = 594;
			this.tblData.HeightRequest = 186;
			this.tblData.Name = "tblData";
			this.tblData.RowSpacing = ((uint)(15));
			this.tblData.ColumnSpacing = ((uint)(10));
			this.tblData.BorderWidth = ((uint)(8));
			// Container child tblData.Gtk.Table+TableChild
			this.lblEmpty = new global::Gtk.Label ();
			this.lblEmpty.WidthRequest = 142;
			this.lblEmpty.HeightRequest = 24;
			this.lblEmpty.Name = "lblEmpty";
			this.lblEmpty.Justify = ((global::Gtk.Justification)(2));
			this.tblData.Add (this.lblEmpty);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblEmpty]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.lblFeet = new global::Gtk.Label ();
			this.lblFeet.WidthRequest = 132;
			this.lblFeet.HeightRequest = 24;
			this.lblFeet.Name = "lblFeet";
			this.lblFeet.LabelProp = global::Mono.Unix.Catalog.GetString ("Feet");
			this.lblFeet.Justify = ((global::Gtk.Justification)(2));
			this.tblData.Add (this.lblFeet);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblFeet]));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.lblInches = new global::Gtk.Label ();
			this.lblInches.WidthRequest = 132;
			this.lblInches.HeightRequest = 24;
			this.lblInches.Name = "lblInches";
			this.lblInches.LabelProp = global::Mono.Unix.Catalog.GetString ("Inches");
			this.lblInches.Justify = ((global::Gtk.Justification)(2));
			this.tblData.Add (this.lblInches);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblInches]));
			w4.LeftAttach = ((uint)(3));
			w4.RightAttach = ((uint)(4));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.lblLength = new global::Gtk.Label ();
			this.lblLength.WidthRequest = 142;
			this.lblLength.HeightRequest = 30;
			this.lblLength.Name = "lblLength";
			this.lblLength.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter length:");
			this.tblData.Add (this.lblLength);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblLength]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.lblWidth = new global::Gtk.Label ();
			this.lblWidth.WidthRequest = 142;
			this.lblWidth.HeightRequest = 30;
			this.lblWidth.Name = "lblWidth";
			this.lblWidth.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter width:");
			this.tblData.Add (this.lblWidth);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblWidth]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.lblYards = new global::Gtk.Label ();
			this.lblYards.WidthRequest = 132;
			this.lblYards.HeightRequest = 24;
			this.lblYards.Name = "lblYards";
			this.lblYards.LabelProp = global::Mono.Unix.Catalog.GetString ("Yards");
			this.lblYards.Justify = ((global::Gtk.Justification)(2));
			this.tblData.Add (this.lblYards);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblYards]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtLengthFeet = new global::Gtk.Entry ();
			this.txtLengthFeet.WidthRequest = 124;
			this.txtLengthFeet.HeightRequest = 30;
			this.txtLengthFeet.CanFocus = true;
			this.txtLengthFeet.Name = "txtLengthFeet";
			this.txtLengthFeet.IsEditable = true;
			this.txtLengthFeet.InvisibleChar = '•';
			this.tblData.Add (this.txtLengthFeet);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtLengthFeet]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(2));
			w8.RightAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtLengthInches = new global::Gtk.Entry ();
			this.txtLengthInches.WidthRequest = 124;
			this.txtLengthInches.HeightRequest = 30;
			this.txtLengthInches.CanFocus = true;
			this.txtLengthInches.Name = "txtLengthInches";
			this.txtLengthInches.IsEditable = true;
			this.txtLengthInches.InvisibleChar = '•';
			this.tblData.Add (this.txtLengthInches);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtLengthInches]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(3));
			w9.RightAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtLengthYard = new global::Gtk.Entry ();
			this.txtLengthYard.WidthRequest = 124;
			this.txtLengthYard.HeightRequest = 30;
			this.txtLengthYard.CanFocus = true;
			this.txtLengthYard.Name = "txtLengthYard";
			this.txtLengthYard.IsEditable = true;
			this.txtLengthYard.InvisibleChar = '•';
			this.tblData.Add (this.txtLengthYard);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtLengthYard]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtWidthFeet = new global::Gtk.Entry ();
			this.txtWidthFeet.WidthRequest = 124;
			this.txtWidthFeet.HeightRequest = 30;
			this.txtWidthFeet.CanFocus = true;
			this.txtWidthFeet.Name = "txtWidthFeet";
			this.txtWidthFeet.IsEditable = true;
			this.txtWidthFeet.InvisibleChar = '•';
			this.tblData.Add (this.txtWidthFeet);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtWidthFeet]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.LeftAttach = ((uint)(2));
			w11.RightAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtWidthInches = new global::Gtk.Entry ();
			this.txtWidthInches.WidthRequest = 124;
			this.txtWidthInches.HeightRequest = 30;
			this.txtWidthInches.CanFocus = true;
			this.txtWidthInches.Name = "txtWidthInches";
			this.txtWidthInches.IsEditable = true;
			this.txtWidthInches.InvisibleChar = '•';
			this.tblData.Add (this.txtWidthInches);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtWidthInches]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(3));
			w12.RightAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtWidthYard = new global::Gtk.Entry ();
			this.txtWidthYard.WidthRequest = 124;
			this.txtWidthYard.HeightRequest = 30;
			this.txtWidthYard.CanFocus = true;
			this.txtWidthYard.Name = "txtWidthYard";
			this.txtWidthYard.IsEditable = true;
			this.txtWidthYard.InvisibleChar = '•';
			this.tblData.Add (this.txtWidthYard);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtWidthYard]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox1.Add (this.tblData);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tblData]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hbox1.Add (this.alignment2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment2]));
			w15.Position = 2;
			this.dialog1_VBox.Add (this.hbox1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.hbox1]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.hbox2.Add (this.alignment4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment4]));
			w17.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.tblCubicTotals = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.tblCubicTotals.WidthRequest = 524;
			this.tblCubicTotals.HeightRequest = 186;
			this.tblCubicTotals.Name = "tblCubicTotals";
			this.tblCubicTotals.RowSpacing = ((uint)(15));
			this.tblCubicTotals.ColumnSpacing = ((uint)(10));
			this.tblCubicTotals.BorderWidth = ((uint)(8));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.alignment11 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.tblCubicTotals.Add (this.alignment11);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.alignment11]));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.alignment12 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.tblCubicTotals.Add (this.alignment12);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.alignment12]));
			w19.LeftAttach = ((uint)(3));
			w19.RightAttach = ((uint)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.lblSurfaceFeet = new global::Gtk.Label ();
			this.lblSurfaceFeet.WidthRequest = 142;
			this.lblSurfaceFeet.HeightRequest = 30;
			this.lblSurfaceFeet.Name = "lblSurfaceFeet";
			this.lblSurfaceFeet.LabelProp = global::Mono.Unix.Catalog.GetString ("Surface Area in Feet:");
			this.tblCubicTotals.Add (this.lblSurfaceFeet);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.lblSurfaceFeet]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.lblSurfaceInches = new global::Gtk.Label ();
			this.lblSurfaceInches.WidthRequest = 142;
			this.lblSurfaceInches.HeightRequest = 30;
			this.lblSurfaceInches.Name = "lblSurfaceInches";
			this.lblSurfaceInches.LabelProp = global::Mono.Unix.Catalog.GetString ("Surface Area in Inches:");
			this.tblCubicTotals.Add (this.lblSurfaceInches);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.lblSurfaceInches]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.lblSurfaceYards = new global::Gtk.Label ();
			this.lblSurfaceYards.WidthRequest = 142;
			this.lblSurfaceYards.HeightRequest = 30;
			this.lblSurfaceYards.Name = "lblSurfaceYards";
			this.lblSurfaceYards.LabelProp = global::Mono.Unix.Catalog.GetString ("Surface Area In Yards:");
			this.tblCubicTotals.Add (this.lblSurfaceYards);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.lblSurfaceYards]));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.txtSurfaceFeet = new global::Gtk.Entry ();
			this.txtSurfaceFeet.WidthRequest = 124;
			this.txtSurfaceFeet.HeightRequest = 30;
			this.txtSurfaceFeet.CanFocus = true;
			this.txtSurfaceFeet.Name = "txtSurfaceFeet";
			this.txtSurfaceFeet.IsEditable = false;
			this.txtSurfaceFeet.InvisibleChar = '•';
			this.tblCubicTotals.Add (this.txtSurfaceFeet);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.txtSurfaceFeet]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.LeftAttach = ((uint)(2));
			w23.RightAttach = ((uint)(3));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.txtSurfaceInches = new global::Gtk.Entry ();
			this.txtSurfaceInches.WidthRequest = 124;
			this.txtSurfaceInches.HeightRequest = 30;
			this.txtSurfaceInches.CanFocus = true;
			this.txtSurfaceInches.Name = "txtSurfaceInches";
			this.txtSurfaceInches.IsEditable = false;
			this.txtSurfaceInches.InvisibleChar = '•';
			this.tblCubicTotals.Add (this.txtSurfaceInches);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.txtSurfaceInches]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.LeftAttach = ((uint)(2));
			w24.RightAttach = ((uint)(3));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.txtSurfaceYards = new global::Gtk.Entry ();
			this.txtSurfaceYards.WidthRequest = 124;
			this.txtSurfaceYards.HeightRequest = 30;
			this.txtSurfaceYards.CanFocus = true;
			this.txtSurfaceYards.Name = "txtSurfaceYards";
			this.txtSurfaceYards.IsEditable = false;
			this.txtSurfaceYards.InvisibleChar = '•';
			this.tblCubicTotals.Add (this.txtSurfaceYards);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.txtSurfaceYards]));
			w25.LeftAttach = ((uint)(2));
			w25.RightAttach = ((uint)(3));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox2.Add (this.tblCubicTotals);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.tblCubicTotals]));
			w26.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.hbox2.Add (this.alignment3);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment3]));
			w27.Position = 2;
			this.dialog1_VBox.Add (this.hbox2);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.hbox2]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hbox8.Add (this.alignment5);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.alignment5]));
			w29.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbtnLeft = new global::Gtk.VButtonBox ();
			this.vbtnLeft.WidthRequest = 142;
			this.vbtnLeft.HeightRequest = 142;
			this.vbtnLeft.Name = "vbtnLeft";
			this.vbtnLeft.Homogeneous = true;
			this.vbtnLeft.BorderWidth = ((uint)(4));
			this.vbtnLeft.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbtnLeft.Gtk.ButtonBox+ButtonBoxChild
			this.btnClear = new global::Gtk.Button ();
			this.btnClear.WidthRequest = 112;
			this.btnClear.HeightRequest = 40;
			this.btnClear.CanFocus = true;
			this.btnClear.Name = "btnClear";
			this.btnClear.UseUnderline = true;
			this.btnClear.BorderWidth = ((uint)(4));
			this.btnClear.Label = global::Mono.Unix.Catalog.GetString ("Clear Form");
			this.vbtnLeft.Add (this.btnClear);
			global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnLeft [this.btnClear]));
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbtnLeft.Gtk.ButtonBox+ButtonBoxChild
			this.btnStandard = new global::Gtk.Button ();
			this.btnStandard.WidthRequest = 112;
			this.btnStandard.HeightRequest = 40;
			this.btnStandard.CanFocus = true;
			this.btnStandard.Name = "btnStandard";
			this.btnStandard.UseUnderline = true;
			this.btnStandard.BorderWidth = ((uint)(4));
			this.btnStandard.Label = global::Mono.Unix.Catalog.GetString ("Standard");
			this.vbtnLeft.Add (this.btnStandard);
			global::Gtk.ButtonBox.ButtonBoxChild w31 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnLeft [this.btnStandard]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbtnLeft.Gtk.ButtonBox+ButtonBoxChild
			this.btnMetric = new global::Gtk.Button ();
			this.btnMetric.WidthRequest = 112;
			this.btnMetric.HeightRequest = 40;
			this.btnMetric.CanFocus = true;
			this.btnMetric.Name = "btnMetric";
			this.btnMetric.UseUnderline = true;
			this.btnMetric.BorderWidth = ((uint)(4));
			this.btnMetric.Label = global::Mono.Unix.Catalog.GetString ("Metric");
			this.vbtnLeft.Add (this.btnMetric);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnLeft [this.btnMetric]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			this.hbox8.Add (this.vbtnLeft);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbtnLeft]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.hbox8.Add (this.alignment6);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.alignment6]));
			w34.Position = 2;
			this.hbox7.Add (this.hbox8);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox8]));
			w35.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.hbox9.Add (this.alignment7);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment7]));
			w36.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbtnCenter = new global::Gtk.VButtonBox ();
			this.vbtnCenter.WidthRequest = 142;
			this.vbtnCenter.HeightRequest = 142;
			this.vbtnCenter.Name = "vbtnCenter";
			this.vbtnCenter.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbtnCenter.Gtk.ButtonBox+ButtonBoxChild
			this.btnSolve = new global::Gtk.Button ();
			this.btnSolve.WidthRequest = 112;
			this.btnSolve.HeightRequest = 40;
			this.btnSolve.CanFocus = true;
			this.btnSolve.Name = "btnSolve";
			this.btnSolve.UseUnderline = true;
			this.btnSolve.BorderWidth = ((uint)(4));
			this.btnSolve.Label = global::Mono.Unix.Catalog.GetString ("Solve");
			this.vbtnCenter.Add (this.btnSolve);
			global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnCenter [this.btnSolve]));
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbtnCenter.Gtk.ButtonBox+ButtonBoxChild
			this.btnStore = new global::Gtk.Button ();
			this.btnStore.WidthRequest = 112;
			this.btnStore.HeightRequest = 40;
			this.btnStore.CanFocus = true;
			this.btnStore.Name = "btnStore";
			this.btnStore.UseUnderline = true;
			this.btnStore.BorderWidth = ((uint)(4));
			this.btnStore.Label = global::Mono.Unix.Catalog.GetString ("Store Result");
			this.vbtnCenter.Add (this.btnStore);
			global::Gtk.ButtonBox.ButtonBoxChild w38 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnCenter [this.btnStore]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbtnCenter.Gtk.ButtonBox+ButtonBoxChild
			this.btnDisplayStore = new global::Gtk.Button ();
			this.btnDisplayStore.WidthRequest = 112;
			this.btnDisplayStore.HeightRequest = 40;
			this.btnDisplayStore.CanFocus = true;
			this.btnDisplayStore.Name = "btnDisplayStore";
			this.btnDisplayStore.UseUnderline = true;
			this.btnDisplayStore.BorderWidth = ((uint)(4));
			this.btnDisplayStore.Label = global::Mono.Unix.Catalog.GetString ("Display Store");
			this.vbtnCenter.Add (this.btnDisplayStore);
			global::Gtk.ButtonBox.ButtonBoxChild w39 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnCenter [this.btnDisplayStore]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbtnCenter.Gtk.ButtonBox+ButtonBoxChild
			this.btnClearStore = new global::Gtk.Button ();
			this.btnClearStore.WidthRequest = 112;
			this.btnClearStore.HeightRequest = 40;
			this.btnClearStore.CanFocus = true;
			this.btnClearStore.Name = "btnClearStore";
			this.btnClearStore.UseUnderline = true;
			this.btnClearStore.BorderWidth = ((uint)(4));
			this.btnClearStore.Label = global::Mono.Unix.Catalog.GetString ("Clear Store");
			this.vbtnCenter.Add (this.btnClearStore);
			global::Gtk.ButtonBox.ButtonBoxChild w40 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnCenter [this.btnClearStore]));
			w40.Position = 3;
			w40.Expand = false;
			w40.Fill = false;
			this.hbox9.Add (this.vbtnCenter);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbtnCenter]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.hbox9.Add (this.alignment8);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment8]));
			w42.Position = 2;
			this.hbox7.Add (this.hbox9);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox9]));
			w43.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.hbox10.Add (this.alignment9);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.alignment9]));
			w44.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbtnRight = new global::Gtk.VButtonBox ();
			this.vbtnRight.WidthRequest = 142;
			this.vbtnRight.HeightRequest = 142;
			this.vbtnRight.Name = "vbtnRight";
			this.vbtnRight.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbtnRight.Gtk.ButtonBox+ButtonBoxChild
			this.btnPrintForm = new global::Gtk.Button ();
			this.btnPrintForm.WidthRequest = 112;
			this.btnPrintForm.HeightRequest = 40;
			this.btnPrintForm.CanFocus = true;
			this.btnPrintForm.Name = "btnPrintForm";
			this.btnPrintForm.UseUnderline = true;
			this.btnPrintForm.BorderWidth = ((uint)(4));
			this.btnPrintForm.Label = global::Mono.Unix.Catalog.GetString ("Print Form");
			this.vbtnRight.Add (this.btnPrintForm);
			global::Gtk.ButtonBox.ButtonBoxChild w45 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnRight [this.btnPrintForm]));
			w45.Expand = false;
			w45.Fill = false;
			// Container child vbtnRight.Gtk.ButtonBox+ButtonBoxChild
			this.btnPrintStored = new global::Gtk.Button ();
			this.btnPrintStored.WidthRequest = 112;
			this.btnPrintStored.HeightRequest = 40;
			this.btnPrintStored.CanFocus = true;
			this.btnPrintStored.Name = "btnPrintStored";
			this.btnPrintStored.UseUnderline = true;
			this.btnPrintStored.BorderWidth = ((uint)(4));
			this.btnPrintStored.Label = global::Mono.Unix.Catalog.GetString ("Print Stored");
			this.vbtnRight.Add (this.btnPrintStored);
			global::Gtk.ButtonBox.ButtonBoxChild w46 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnRight [this.btnPrintStored]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbtnRight.Gtk.ButtonBox+ButtonBoxChild
			this.btnSaveForm = new global::Gtk.Button ();
			this.btnSaveForm.WidthRequest = 112;
			this.btnSaveForm.HeightRequest = 40;
			this.btnSaveForm.CanFocus = true;
			this.btnSaveForm.Name = "btnSaveForm";
			this.btnSaveForm.UseUnderline = true;
			this.btnSaveForm.BorderWidth = ((uint)(4));
			this.btnSaveForm.Label = global::Mono.Unix.Catalog.GetString ("Save Form");
			this.vbtnRight.Add (this.btnSaveForm);
			global::Gtk.ButtonBox.ButtonBoxChild w47 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnRight [this.btnSaveForm]));
			w47.Position = 2;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vbtnRight.Gtk.ButtonBox+ButtonBoxChild
			this.btnClose = new global::Gtk.Button ();
			this.btnClose.WidthRequest = 112;
			this.btnClose.HeightRequest = 40;
			this.btnClose.CanFocus = true;
			this.btnClose.Name = "btnClose";
			this.btnClose.UseStock = true;
			this.btnClose.UseUnderline = true;
			this.btnClose.BorderWidth = ((uint)(4));
			this.btnClose.Label = "gtk-close";
			this.vbtnRight.Add (this.btnClose);
			global::Gtk.ButtonBox.ButtonBoxChild w48 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnRight [this.btnClose]));
			w48.Position = 3;
			w48.Expand = false;
			w48.Fill = false;
			this.hbox10.Add (this.vbtnRight);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbtnRight]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			this.hbox10.Add (this.alignment10);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.alignment10]));
			w50.Position = 2;
			this.hbox7.Add (this.hbox10);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox10]));
			w51.Position = 2;
			this.dialog1_VBox.Add (this.hbox7);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.hbox7]));
			w52.Position = 2;
			this.Add (this.dialog1_VBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			this.Show ();
			this.btnClear.Clicked += new global::System.EventHandler (this.OnBtnClearFormClicked);
			this.btnStandard.Clicked += new global::System.EventHandler (this.OnBtnStandardClicked);
			this.btnMetric.Clicked += new global::System.EventHandler (this.OnBtnMetricClicked);
			this.btnSolve.Clicked += new global::System.EventHandler (this.OnBtnSolveClicked);
			this.btnStore.Clicked += new global::System.EventHandler (this.OnBtnStoreResultClicked);
			this.btnDisplayStore.Clicked += new global::System.EventHandler (this.OnBtnDisplayStoreClicked);
			this.btnClearStore.Clicked += new global::System.EventHandler (this.OnBtnClearStoreClicked);
			this.btnPrintForm.Clicked += new global::System.EventHandler (this.OnBtnPrintFormClicked);
			this.btnPrintStored.Clicked += new global::System.EventHandler (this.OnBtnPrintStoredClicked);
			this.btnSaveForm.Clicked += new global::System.EventHandler (this.OnBtnSaveFormClicked);
			this.btnClose.Clicked += new global::System.EventHandler (this.OnBtnCloseClicked);
		}
	}
}
