
// This file has been generated by the GUI designer. Do not modify.
namespace BuildingFormulas
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action FileAction;
		
		private global::Gtk.Action QuitBuildingFormulasAction;
		
		private global::Gtk.Action FormulasAction;
		
		private global::Gtk.Action CubicAreaAction;
		
		private global::Gtk.Action CubicAreaSquareAction;
		
		private global::Gtk.Action CubicAreaSquareAction1;
		
		private global::Gtk.Action CubicAreaRectangleAction;
		
		private global::Gtk.Action CubicAreaCircleAction;
		
		private global::Gtk.Action CubicAreaCylinderAction;
		
		private global::Gtk.Action CubicAreaOvalAction;
		
		private global::Gtk.Action CubicAreaConeAction;
		
		private global::Gtk.Action CubicAreaPyramidAction;
		
		private global::Gtk.Action CubicAreaHexagonAction;
		
		private global::Gtk.Action CubicAreaOctagonAction;
		
		private global::Gtk.Action CubicAreaTriangleAction;
		
		private global::Gtk.Action WithRectangleBaseAction;
		
		private global::Gtk.Action WithTriangleBaseAction;
		
		private global::Gtk.Action WithSquareBaseAction;
		
		private global::Gtk.Action WithSquareBaseAction1;
		
		private global::Gtk.Action CubicAreaCircleAction1;
		
		private global::Gtk.Action CubicAreaTriangleAction1;
		
		private global::Gtk.Action CubicAreaRectangleAction1;
		
		private global::Gtk.Action CubicAreaSquareAction2;
		
		private global::Gtk.Action SurfaceAreaAction;
		
		private global::Gtk.Action CircleAction;
		
		private global::Gtk.Action CylinderAction;
		
		private global::Gtk.Action ConeAction;
		
		private global::Gtk.Action PyramidAction;
		
		private global::Gtk.Action TriangleAction;
		
		private global::Gtk.Action HexagonAction;
		
		private global::Gtk.Action OctagonAction;
		
		private global::Gtk.Action RectangleAction;
		
		private global::Gtk.Action SquareAction;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar mnuMain;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.HButtonBox hbuttonbox1;
		
		private global::Gtk.Button btnQuit;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BuildingFormulas.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.QuitBuildingFormulasAction = new global::Gtk.Action ("QuitBuildingFormulasAction", global::Mono.Unix.Catalog.GetString ("Quit Building Formulas"), null, null);
			this.QuitBuildingFormulasAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit Building Formulas");
			w1.Add (this.QuitBuildingFormulasAction, null);
			this.FormulasAction = new global::Gtk.Action ("FormulasAction", global::Mono.Unix.Catalog.GetString ("Formulas"), null, null);
			this.FormulasAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Formulas");
			w1.Add (this.FormulasAction, null);
			this.CubicAreaAction = new global::Gtk.Action ("CubicAreaAction", global::Mono.Unix.Catalog.GetString ("Cubic Area "), null, null);
			this.CubicAreaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Shapes Area");
			w1.Add (this.CubicAreaAction, null);
			this.CubicAreaSquareAction = new global::Gtk.Action ("CubicAreaSquareAction", global::Mono.Unix.Catalog.GetString ("Cubic Area Square"), null, null);
			this.CubicAreaSquareAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Square");
			w1.Add (this.CubicAreaSquareAction, null);
			this.CubicAreaSquareAction1 = new global::Gtk.Action ("CubicAreaSquareAction1", global::Mono.Unix.Catalog.GetString ("Cubic Area Square"), null, null);
			this.CubicAreaSquareAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Square");
			w1.Add (this.CubicAreaSquareAction1, null);
			this.CubicAreaRectangleAction = new global::Gtk.Action ("CubicAreaRectangleAction", global::Mono.Unix.Catalog.GetString ("Cubic Area Rectangle"), null, null);
			this.CubicAreaRectangleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Rectangle");
			w1.Add (this.CubicAreaRectangleAction, null);
			this.CubicAreaCircleAction = new global::Gtk.Action ("CubicAreaCircleAction", global::Mono.Unix.Catalog.GetString ("Cubic Area Circle"), null, null);
			this.CubicAreaCircleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Circle");
			w1.Add (this.CubicAreaCircleAction, null);
			this.CubicAreaCylinderAction = new global::Gtk.Action ("CubicAreaCylinderAction", global::Mono.Unix.Catalog.GetString ("Cubic Area Cylinder"), null, null);
			this.CubicAreaCylinderAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Cylinder");
			w1.Add (this.CubicAreaCylinderAction, null);
			this.CubicAreaOvalAction = new global::Gtk.Action ("CubicAreaOvalAction", global::Mono.Unix.Catalog.GetString ("Cubic Area Oval"), null, null);
			this.CubicAreaOvalAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Oval");
			w1.Add (this.CubicAreaOvalAction, null);
			this.CubicAreaConeAction = new global::Gtk.Action ("CubicAreaConeAction", global::Mono.Unix.Catalog.GetString ("Cubic Area Cone"), null, null);
			this.CubicAreaConeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Cone");
			w1.Add (this.CubicAreaConeAction, null);
			this.CubicAreaPyramidAction = new global::Gtk.Action ("CubicAreaPyramidAction", global::Mono.Unix.Catalog.GetString ("Cubic Area Pyramid"), null, null);
			this.CubicAreaPyramidAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Pyramid");
			w1.Add (this.CubicAreaPyramidAction, null);
			this.CubicAreaHexagonAction = new global::Gtk.Action ("CubicAreaHexagonAction", global::Mono.Unix.Catalog.GetString ("Cubic Area Hexagon"), null, null);
			this.CubicAreaHexagonAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Hexagon");
			w1.Add (this.CubicAreaHexagonAction, null);
			this.CubicAreaOctagonAction = new global::Gtk.Action ("CubicAreaOctagonAction", global::Mono.Unix.Catalog.GetString ("Cubic Area Octagon"), null, null);
			this.CubicAreaOctagonAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Octagon");
			w1.Add (this.CubicAreaOctagonAction, null);
			this.CubicAreaTriangleAction = new global::Gtk.Action ("CubicAreaTriangleAction", global::Mono.Unix.Catalog.GetString ("Cubic Area Triangle"), null, null);
			this.CubicAreaTriangleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Triangle");
			w1.Add (this.CubicAreaTriangleAction, null);
			this.WithRectangleBaseAction = new global::Gtk.Action ("WithRectangleBaseAction", global::Mono.Unix.Catalog.GetString ("With Rectangle Base"), null, null);
			this.WithRectangleBaseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("With Rectangle Base");
			w1.Add (this.WithRectangleBaseAction, null);
			this.WithTriangleBaseAction = new global::Gtk.Action ("WithTriangleBaseAction", global::Mono.Unix.Catalog.GetString ("With Triangle Base"), null, null);
			this.WithTriangleBaseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("With Triangle Base");
			w1.Add (this.WithTriangleBaseAction, null);
			this.WithSquareBaseAction = new global::Gtk.Action ("WithSquareBaseAction", global::Mono.Unix.Catalog.GetString ("With Square Base"), null, null);
			this.WithSquareBaseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("With Square Base");
			w1.Add (this.WithSquareBaseAction, null);
			this.WithSquareBaseAction1 = new global::Gtk.Action ("WithSquareBaseAction1", global::Mono.Unix.Catalog.GetString ("With Square Base"), null, null);
			this.WithSquareBaseAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("With Square Base");
			w1.Add (this.WithSquareBaseAction1, null);
			this.CubicAreaCircleAction1 = new global::Gtk.Action ("CubicAreaCircleAction1", global::Mono.Unix.Catalog.GetString ("Cubic Area Circle"), null, null);
			this.CubicAreaCircleAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Circle");
			w1.Add (this.CubicAreaCircleAction1, null);
			this.CubicAreaTriangleAction1 = new global::Gtk.Action ("CubicAreaTriangleAction1", global::Mono.Unix.Catalog.GetString ("Cubic Area Triangle"), null, null);
			this.CubicAreaTriangleAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Triangle");
			w1.Add (this.CubicAreaTriangleAction1, null);
			this.CubicAreaRectangleAction1 = new global::Gtk.Action ("CubicAreaRectangleAction1", global::Mono.Unix.Catalog.GetString ("Cubic Area Rectangle"), null, null);
			this.CubicAreaRectangleAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Rectangle");
			w1.Add (this.CubicAreaRectangleAction1, null);
			this.CubicAreaSquareAction2 = new global::Gtk.Action ("CubicAreaSquareAction2", global::Mono.Unix.Catalog.GetString ("Cubic Area Square"), null, null);
			this.CubicAreaSquareAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cubic Area Square");
			w1.Add (this.CubicAreaSquareAction2, null);
			this.SurfaceAreaAction = new global::Gtk.Action ("SurfaceAreaAction", global::Mono.Unix.Catalog.GetString ("Surface Area"), null, null);
			this.SurfaceAreaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Surface Area");
			w1.Add (this.SurfaceAreaAction, null);
			this.CircleAction = new global::Gtk.Action ("CircleAction", global::Mono.Unix.Catalog.GetString ("Circle"), null, null);
			this.CircleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Circle");
			w1.Add (this.CircleAction, null);
			this.CylinderAction = new global::Gtk.Action ("CylinderAction", global::Mono.Unix.Catalog.GetString ("Cylinder"), null, null);
			this.CylinderAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cylinder");
			w1.Add (this.CylinderAction, null);
			this.ConeAction = new global::Gtk.Action ("ConeAction", global::Mono.Unix.Catalog.GetString ("Cone"), null, null);
			this.ConeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cone");
			w1.Add (this.ConeAction, null);
			this.PyramidAction = new global::Gtk.Action ("PyramidAction", global::Mono.Unix.Catalog.GetString ("Pyramid"), null, null);
			this.PyramidAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Pyramid");
			w1.Add (this.PyramidAction, null);
			this.TriangleAction = new global::Gtk.Action ("TriangleAction", global::Mono.Unix.Catalog.GetString ("Triangle"), null, null);
			this.TriangleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Triangle");
			w1.Add (this.TriangleAction, null);
			this.HexagonAction = new global::Gtk.Action ("HexagonAction", global::Mono.Unix.Catalog.GetString ("Hexagon"), null, null);
			this.HexagonAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Hexagon");
			w1.Add (this.HexagonAction, null);
			this.OctagonAction = new global::Gtk.Action ("OctagonAction", global::Mono.Unix.Catalog.GetString ("Octagon"), null, null);
			this.OctagonAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Octagon");
			w1.Add (this.OctagonAction, null);
			this.RectangleAction = new global::Gtk.Action ("RectangleAction", global::Mono.Unix.Catalog.GetString ("Rectangle"), null, null);
			this.RectangleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Rectangle");
			w1.Add (this.RectangleAction, null);
			this.SquareAction = new global::Gtk.Action ("SquareAction", global::Mono.Unix.Catalog.GetString ("Square"), null, null);
			this.SquareAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Square");
			w1.Add (this.SquareAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.WidthRequest = 800;
			this.HeightRequest = 700;
			this.Name = "BuildingFormulas.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Building Formulas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(8));
			this.DefaultWidth = 800;
			this.DefaultHeight = 700;
			// Container child BuildingFormulas.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='mnuMain'><menu name='FileAction' action='FileAction'><menuitem name='QuitBuildingFormulasAction' action='QuitBuildingFormulasAction'/></menu><menu name='FormulasAction' action='FormulasAction'><menu name='CubicAreaAction' action='CubicAreaAction'><separator/><menuitem name='CubicAreaCircleAction1' action='CubicAreaCircleAction1'/><menuitem name='CubicAreaCylinderAction' action='CubicAreaCylinderAction'/><separator/><menuitem name='CubicAreaConeAction' action='CubicAreaConeAction'/><menu name='CubicAreaPyramidAction' action='CubicAreaPyramidAction'><menuitem name='WithRectangleBaseAction' action='WithRectangleBaseAction'/><menuitem name='WithSquareBaseAction1' action='WithSquareBaseAction1'/><menuitem name='WithTriangleBaseAction' action='WithTriangleBaseAction'/></menu><menuitem name='CubicAreaTriangleAction1' action='CubicAreaTriangleAction1'/><separator/><menuitem name='CubicAreaHexagonAction' action='CubicAreaHexagonAction'/><menuitem name='CubicAreaOctagonAction' action='CubicAreaOctagonAction'/><separator/><menuitem name='CubicAreaRectangleAction1' action='CubicAreaRectangleAction1'/><menuitem name='CubicAreaSquareAction2' action='CubicAreaSquareAction2'/></menu><menu name='SurfaceAreaAction' action='SurfaceAreaAction'><menuitem name='CircleAction' action='CircleAction'/><menuitem name='CylinderAction' action='CylinderAction'/><separator/><menuitem name='ConeAction' action='ConeAction'/><menuitem name='PyramidAction' action='PyramidAction'/><menuitem name='TriangleAction' action='TriangleAction'/><separator/><menuitem name='HexagonAction' action='HexagonAction'/><menuitem name='OctagonAction' action='OctagonAction'/><separator/><menuitem name='RectangleAction' action='RectangleAction'/><menuitem name='SquareAction' action='SquareAction'/></menu></menu></menubar></ui>");
			this.mnuMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/mnuMain")));
			this.mnuMain.Name = "mnuMain";
			this.vbox1.Add (this.mnuMain);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.mnuMain]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.vbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment1]));
			w3.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.HeightRequest = 46;
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.BorderWidth = ((uint)(4));
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnQuit = new global::Gtk.Button ();
			this.btnQuit.WidthRequest = 96;
			this.btnQuit.HeightRequest = 36;
			this.btnQuit.CanFocus = true;
			this.btnQuit.Name = "btnQuit";
			this.btnQuit.UseStock = true;
			this.btnQuit.UseUnderline = true;
			this.btnQuit.BorderWidth = ((uint)(2));
			this.btnQuit.Label = "gtk-quit";
			this.hbuttonbox1.Add (this.btnQuit);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnQuit]));
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.QuitBuildingFormulasAction.Activated += new global::System.EventHandler (this.OnQuitBuildingFormulasActionActivated);
			this.CubicAreaSquareAction1.Activated += new global::System.EventHandler (this.OnCubicAreaSquareActionActivated);
			this.CubicAreaRectangleAction.Activated += new global::System.EventHandler (this.OnCubicAreaRectangleActionActivated);
			this.CubicAreaCylinderAction.Activated += new global::System.EventHandler (this.OnCubicAreaCylinderActionActivated);
			this.CubicAreaConeAction.Activated += new global::System.EventHandler (this.OnCubicAreaConeActionActivated);
			this.CubicAreaHexagonAction.Activated += new global::System.EventHandler (this.OnCubicAreaHexagonActionActivated);
			this.CubicAreaOctagonAction.Activated += new global::System.EventHandler (this.OnCubicAreaOctagonActionActivated);
			this.WithRectangleBaseAction.Activated += new global::System.EventHandler (this.OnBtnPyramidRectangelBaseActionActivated);
			this.WithTriangleBaseAction.Activated += new global::System.EventHandler (this.OnBtnPyramidWithTriangleBaseActionActivated);
			this.WithSquareBaseAction1.Activated += new global::System.EventHandler (this.OnBtnPyramidSquareBaseActionActivated);
			this.CubicAreaCircleAction1.Activated += new global::System.EventHandler (this.OnBtnCubicAreaCircleActionActivated);
			this.CubicAreaTriangleAction1.Activated += new global::System.EventHandler (this.OnBtnCubicAreaTriangleActionActivated);
			this.CubicAreaRectangleAction1.Activated += new global::System.EventHandler (this.OnCubicAreaRectangleActionActivated);
			this.CubicAreaSquareAction2.Activated += new global::System.EventHandler (this.OnCubicAreaSquareActionActivated);
			this.CircleAction.Activated += new global::System.EventHandler (this.OnMenuCircleSurfaceAreaActivated);
			this.CylinderAction.Activated += new global::System.EventHandler (this.OnMenuCylinderSurfaceAreaActivated);
			this.ConeAction.Activated += new global::System.EventHandler (this.OnMenuConeSurfaceAreaActivated);
			this.PyramidAction.Activated += new global::System.EventHandler (this.OnMenuPyramidSurfaceAreaActivated);
			this.TriangleAction.Activated += new global::System.EventHandler (this.OnMenuTriangleSurfaceAreaActivated);
			this.HexagonAction.Activated += new global::System.EventHandler (this.OnMenuHexagonSurfaceAreaActivated);
			this.OctagonAction.Activated += new global::System.EventHandler (this.OnMenuOctagonSurfaceAreaActivated);
			this.RectangleAction.Activated += new global::System.EventHandler (this.OnMenuRectangleSurfaceAreaActivated);
			this.SquareAction.Activated += new global::System.EventHandler (this.OnMenuSquareSurfaceAreaActivated);
			this.btnQuit.Clicked += new global::System.EventHandler (this.OnBtnQuitClicked);
		}
	}
}
