
// This file has been generated by the GUI designer. Do not modify.
namespace BuildingFormulas
{
	public partial class DataEntryWindow
	{
		private global::Gtk.VBox dialog1_VBox;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.Table tblData;
		
		private global::Gtk.Label lblEmpty;
		
		private global::Gtk.Label lblEnter1;
		
		private global::Gtk.Label lblEnter2;
		
		private global::Gtk.Label lblEnter3;
		
		private global::Gtk.Label lblFeet;
		
		private global::Gtk.Label lblInches;
		
		private global::Gtk.Label lblYards;
		
		private global::Gtk.Entry txtBoxFeet1;
		
		private global::Gtk.Entry txtBoxFeet2;
		
		private global::Gtk.Entry txtBoxFeet3;
		
		private global::Gtk.Entry txtBoxInches1;
		
		private global::Gtk.Entry txtBoxInches2;
		
		private global::Gtk.Entry txtBoxInches3;
		
		private global::Gtk.Entry txtBoxYard1;
		
		private global::Gtk.Entry txtBoxYard2;
		
		private global::Gtk.Entry txtBoxYard3;
		
		private global::Gtk.Alignment alignment2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Alignment alignment4;
		
		private global::Gtk.Table tblCubicTotals;
		
		private global::Gtk.Alignment alignment11;
		
		private global::Gtk.Alignment alignment12;
		
		private global::Gtk.Label lblCubicFeet;
		
		private global::Gtk.Label lblCubicInches;
		
		private global::Gtk.Label lblCubicYards;
		
		private global::Gtk.Entry txtCubicFeet;
		
		private global::Gtk.Entry txtCubicInches;
		
		private global::Gtk.Entry txtCubicYards;
		
		private global::Gtk.Alignment alignment3;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Alignment alignment5;
		
		private global::Gtk.VButtonBox vbtnLeft;
		
		private global::Gtk.Button btnClear;
		
		private global::Gtk.Button btnStandardMetric;
		
		private global::Gtk.Button btnMetric;
		
		private global::Gtk.Alignment alignment6;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Alignment alignment7;
		
		private global::Gtk.VButtonBox vbtnCenter;
		
		private global::Gtk.Button btnSolve;
		
		private global::Gtk.Button btnStore;
		
		private global::Gtk.Button btnDisplayStore;
		
		private global::Gtk.Button btnClearStore;
		
		private global::Gtk.Alignment alignment8;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Alignment alignment9;
		
		private global::Gtk.VButtonBox vbtnRight;
		
		private global::Gtk.Button btnPrintForm;
		
		private global::Gtk.Button btnPrintStored;
		
		private global::Gtk.Button btnSaveForm;
		
		private global::Gtk.Button btnClose;
		
		private global::Gtk.Alignment alignment10;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BuildingFormulas.DataEntryWindow
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "BuildingFormulas.DataEntryWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("DataEntryWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(8));
			// Container child BuildingFormulas.DataEntryWindow.Gtk.Container+ContainerChild
			this.dialog1_VBox = new global::Gtk.VBox ();
			this.dialog1_VBox.Name = "dialog1_VBox";
			this.dialog1_VBox.BorderWidth = ((uint)(6));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tblData = new global::Gtk.Table (((uint)(4)), ((uint)(4)), false);
			this.tblData.WidthRequest = 594;
			this.tblData.HeightRequest = 186;
			this.tblData.Name = "tblData";
			this.tblData.RowSpacing = ((uint)(15));
			this.tblData.ColumnSpacing = ((uint)(10));
			this.tblData.BorderWidth = ((uint)(8));
			// Container child tblData.Gtk.Table+TableChild
			this.lblEmpty = new global::Gtk.Label ();
			this.lblEmpty.WidthRequest = 142;
			this.lblEmpty.HeightRequest = 24;
			this.lblEmpty.Name = "lblEmpty";
			this.lblEmpty.Justify = ((global::Gtk.Justification)(2));
			this.tblData.Add (this.lblEmpty);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblEmpty]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.lblEnter1 = new global::Gtk.Label ();
			this.lblEnter1.WidthRequest = 142;
			this.lblEnter1.HeightRequest = 30;
			this.lblEnter1.Name = "lblEnter1";
			this.lblEnter1.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter Label 1 Item:");
			this.tblData.Add (this.lblEnter1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblEnter1]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.lblEnter2 = new global::Gtk.Label ();
			this.lblEnter2.WidthRequest = 142;
			this.lblEnter2.HeightRequest = 30;
			this.lblEnter2.Name = "lblEnter2";
			this.lblEnter2.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter Label 2 Item:");
			this.tblData.Add (this.lblEnter2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblEnter2]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.lblEnter3 = new global::Gtk.Label ();
			this.lblEnter3.WidthRequest = 142;
			this.lblEnter3.HeightRequest = 30;
			this.lblEnter3.Name = "lblEnter3";
			this.lblEnter3.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter Label 3 Item:");
			this.tblData.Add (this.lblEnter3);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblEnter3]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.lblFeet = new global::Gtk.Label ();
			this.lblFeet.WidthRequest = 132;
			this.lblFeet.HeightRequest = 24;
			this.lblFeet.Name = "lblFeet";
			this.lblFeet.LabelProp = global::Mono.Unix.Catalog.GetString ("Feet");
			this.lblFeet.Justify = ((global::Gtk.Justification)(2));
			this.tblData.Add (this.lblFeet);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblFeet]));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.lblInches = new global::Gtk.Label ();
			this.lblInches.WidthRequest = 132;
			this.lblInches.HeightRequest = 24;
			this.lblInches.Name = "lblInches";
			this.lblInches.LabelProp = global::Mono.Unix.Catalog.GetString ("Inches");
			this.lblInches.Justify = ((global::Gtk.Justification)(2));
			this.tblData.Add (this.lblInches);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblInches]));
			w7.LeftAttach = ((uint)(3));
			w7.RightAttach = ((uint)(4));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.lblYards = new global::Gtk.Label ();
			this.lblYards.WidthRequest = 132;
			this.lblYards.HeightRequest = 24;
			this.lblYards.Name = "lblYards";
			this.lblYards.LabelProp = global::Mono.Unix.Catalog.GetString ("Yards");
			this.lblYards.Justify = ((global::Gtk.Justification)(2));
			this.tblData.Add (this.lblYards);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tblData [this.lblYards]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtBoxFeet1 = new global::Gtk.Entry ();
			this.txtBoxFeet1.WidthRequest = 124;
			this.txtBoxFeet1.HeightRequest = 30;
			this.txtBoxFeet1.CanFocus = true;
			this.txtBoxFeet1.Name = "txtBoxFeet1";
			this.txtBoxFeet1.IsEditable = true;
			this.txtBoxFeet1.InvisibleChar = '•';
			this.tblData.Add (this.txtBoxFeet1);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtBoxFeet1]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtBoxFeet2 = new global::Gtk.Entry ();
			this.txtBoxFeet2.WidthRequest = 124;
			this.txtBoxFeet2.HeightRequest = 30;
			this.txtBoxFeet2.CanFocus = true;
			this.txtBoxFeet2.Name = "txtBoxFeet2";
			this.txtBoxFeet2.IsEditable = true;
			this.txtBoxFeet2.InvisibleChar = '•';
			this.tblData.Add (this.txtBoxFeet2);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtBoxFeet2]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtBoxFeet3 = new global::Gtk.Entry ();
			this.txtBoxFeet3.WidthRequest = 124;
			this.txtBoxFeet3.HeightRequest = 30;
			this.txtBoxFeet3.CanFocus = true;
			this.txtBoxFeet3.Name = "txtBoxFeet3";
			this.txtBoxFeet3.IsEditable = true;
			this.txtBoxFeet3.InvisibleChar = '•';
			this.tblData.Add (this.txtBoxFeet3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtBoxFeet3]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.LeftAttach = ((uint)(2));
			w11.RightAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtBoxInches1 = new global::Gtk.Entry ();
			this.txtBoxInches1.WidthRequest = 124;
			this.txtBoxInches1.HeightRequest = 30;
			this.txtBoxInches1.CanFocus = true;
			this.txtBoxInches1.Name = "txtBoxInches1";
			this.txtBoxInches1.IsEditable = true;
			this.txtBoxInches1.InvisibleChar = '•';
			this.tblData.Add (this.txtBoxInches1);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtBoxInches1]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(3));
			w12.RightAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtBoxInches2 = new global::Gtk.Entry ();
			this.txtBoxInches2.WidthRequest = 124;
			this.txtBoxInches2.HeightRequest = 30;
			this.txtBoxInches2.CanFocus = true;
			this.txtBoxInches2.Name = "txtBoxInches2";
			this.txtBoxInches2.IsEditable = true;
			this.txtBoxInches2.InvisibleChar = '•';
			this.tblData.Add (this.txtBoxInches2);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtBoxInches2]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.LeftAttach = ((uint)(3));
			w13.RightAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtBoxInches3 = new global::Gtk.Entry ();
			this.txtBoxInches3.WidthRequest = 124;
			this.txtBoxInches3.HeightRequest = 30;
			this.txtBoxInches3.CanFocus = true;
			this.txtBoxInches3.Name = "txtBoxInches3";
			this.txtBoxInches3.IsEditable = true;
			this.txtBoxInches3.InvisibleChar = '•';
			this.tblData.Add (this.txtBoxInches3);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtBoxInches3]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.LeftAttach = ((uint)(3));
			w14.RightAttach = ((uint)(4));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtBoxYard1 = new global::Gtk.Entry ();
			this.txtBoxYard1.WidthRequest = 132;
			this.txtBoxYard1.HeightRequest = 30;
			this.txtBoxYard1.CanFocus = true;
			this.txtBoxYard1.Name = "txtBoxYard1";
			this.txtBoxYard1.IsEditable = true;
			this.txtBoxYard1.InvisibleChar = '•';
			this.tblData.Add (this.txtBoxYard1);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtBoxYard1]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtBoxYard2 = new global::Gtk.Entry ();
			this.txtBoxYard2.WidthRequest = 124;
			this.txtBoxYard2.HeightRequest = 30;
			this.txtBoxYard2.CanFocus = true;
			this.txtBoxYard2.Name = "txtBoxYard2";
			this.txtBoxYard2.IsEditable = true;
			this.txtBoxYard2.InvisibleChar = '•';
			this.tblData.Add (this.txtBoxYard2);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtBoxYard2]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblData.Gtk.Table+TableChild
			this.txtBoxYard3 = new global::Gtk.Entry ();
			this.txtBoxYard3.WidthRequest = 124;
			this.txtBoxYard3.HeightRequest = 30;
			this.txtBoxYard3.CanFocus = true;
			this.txtBoxYard3.Name = "txtBoxYard3";
			this.txtBoxYard3.IsEditable = true;
			this.txtBoxYard3.InvisibleChar = '•';
			this.tblData.Add (this.txtBoxYard3);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tblData [this.txtBoxYard3]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox1.Add (this.tblData);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tblData]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hbox1.Add (this.alignment2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment2]));
			w19.Position = 2;
			this.dialog1_VBox.Add (this.hbox1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.hbox1]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.hbox2.Add (this.alignment4);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment4]));
			w21.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.tblCubicTotals = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.tblCubicTotals.WidthRequest = 524;
			this.tblCubicTotals.HeightRequest = 186;
			this.tblCubicTotals.Name = "tblCubicTotals";
			this.tblCubicTotals.RowSpacing = ((uint)(15));
			this.tblCubicTotals.ColumnSpacing = ((uint)(10));
			this.tblCubicTotals.BorderWidth = ((uint)(8));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.alignment11 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.tblCubicTotals.Add (this.alignment11);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.alignment11]));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.alignment12 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.tblCubicTotals.Add (this.alignment12);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.alignment12]));
			w23.LeftAttach = ((uint)(3));
			w23.RightAttach = ((uint)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.lblCubicFeet = new global::Gtk.Label ();
			this.lblCubicFeet.WidthRequest = 142;
			this.lblCubicFeet.HeightRequest = 30;
			this.lblCubicFeet.Name = "lblCubicFeet";
			this.lblCubicFeet.LabelProp = global::Mono.Unix.Catalog.GetString ("Area in Cubic Feet:");
			this.tblCubicTotals.Add (this.lblCubicFeet);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.lblCubicFeet]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.lblCubicInches = new global::Gtk.Label ();
			this.lblCubicInches.WidthRequest = 142;
			this.lblCubicInches.HeightRequest = 30;
			this.lblCubicInches.Name = "lblCubicInches";
			this.lblCubicInches.LabelProp = global::Mono.Unix.Catalog.GetString ("Area in Cubic Inches:");
			this.tblCubicTotals.Add (this.lblCubicInches);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.lblCubicInches]));
			w25.TopAttach = ((uint)(2));
			w25.BottomAttach = ((uint)(3));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.lblCubicYards = new global::Gtk.Label ();
			this.lblCubicYards.WidthRequest = 142;
			this.lblCubicYards.HeightRequest = 30;
			this.lblCubicYards.Name = "lblCubicYards";
			this.lblCubicYards.LabelProp = global::Mono.Unix.Catalog.GetString ("Area in Cubic Yards:");
			this.tblCubicTotals.Add (this.lblCubicYards);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.lblCubicYards]));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.txtCubicFeet = new global::Gtk.Entry ();
			this.txtCubicFeet.WidthRequest = 124;
			this.txtCubicFeet.HeightRequest = 30;
			this.txtCubicFeet.Sensitive = false;
			this.txtCubicFeet.CanFocus = true;
			this.txtCubicFeet.Name = "txtCubicFeet";
			this.txtCubicFeet.IsEditable = false;
			this.txtCubicFeet.InvisibleChar = '•';
			this.tblCubicTotals.Add (this.txtCubicFeet);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.txtCubicFeet]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.LeftAttach = ((uint)(2));
			w27.RightAttach = ((uint)(3));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.txtCubicInches = new global::Gtk.Entry ();
			this.txtCubicInches.WidthRequest = 124;
			this.txtCubicInches.HeightRequest = 30;
			this.txtCubicInches.Sensitive = false;
			this.txtCubicInches.CanFocus = true;
			this.txtCubicInches.Name = "txtCubicInches";
			this.txtCubicInches.IsEditable = false;
			this.txtCubicInches.InvisibleChar = '•';
			this.tblCubicTotals.Add (this.txtCubicInches);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.txtCubicInches]));
			w28.TopAttach = ((uint)(2));
			w28.BottomAttach = ((uint)(3));
			w28.LeftAttach = ((uint)(2));
			w28.RightAttach = ((uint)(3));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCubicTotals.Gtk.Table+TableChild
			this.txtCubicYards = new global::Gtk.Entry ();
			this.txtCubicYards.WidthRequest = 124;
			this.txtCubicYards.HeightRequest = 30;
			this.txtCubicYards.Sensitive = false;
			this.txtCubicYards.CanFocus = true;
			this.txtCubicYards.Name = "txtCubicYards";
			this.txtCubicYards.IsEditable = false;
			this.txtCubicYards.InvisibleChar = '•';
			this.tblCubicTotals.Add (this.txtCubicYards);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.tblCubicTotals [this.txtCubicYards]));
			w29.LeftAttach = ((uint)(2));
			w29.RightAttach = ((uint)(3));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox2.Add (this.tblCubicTotals);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.tblCubicTotals]));
			w30.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.hbox2.Add (this.alignment3);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment3]));
			w31.Position = 2;
			this.dialog1_VBox.Add (this.hbox2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.hbox2]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hbox8.Add (this.alignment5);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.alignment5]));
			w33.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbtnLeft = new global::Gtk.VButtonBox ();
			this.vbtnLeft.WidthRequest = 142;
			this.vbtnLeft.HeightRequest = 142;
			this.vbtnLeft.Name = "vbtnLeft";
			this.vbtnLeft.BorderWidth = ((uint)(4));
			this.vbtnLeft.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbtnLeft.Gtk.ButtonBox+ButtonBoxChild
			this.btnClear = new global::Gtk.Button ();
			this.btnClear.WidthRequest = 112;
			this.btnClear.HeightRequest = 40;
			this.btnClear.CanFocus = true;
			this.btnClear.Name = "btnClear";
			this.btnClear.UseUnderline = true;
			this.btnClear.BorderWidth = ((uint)(4));
			this.btnClear.Label = global::Mono.Unix.Catalog.GetString ("Clear Form");
			this.vbtnLeft.Add (this.btnClear);
			global::Gtk.ButtonBox.ButtonBoxChild w34 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnLeft [this.btnClear]));
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbtnLeft.Gtk.ButtonBox+ButtonBoxChild
			this.btnStandardMetric = new global::Gtk.Button ();
			this.btnStandardMetric.WidthRequest = 112;
			this.btnStandardMetric.HeightRequest = 40;
			this.btnStandardMetric.CanFocus = true;
			this.btnStandardMetric.Name = "btnStandardMetric";
			this.btnStandardMetric.UseUnderline = true;
			this.btnStandardMetric.BorderWidth = ((uint)(4));
			this.btnStandardMetric.Label = global::Mono.Unix.Catalog.GetString ("Standard");
			this.vbtnLeft.Add (this.btnStandardMetric);
			global::Gtk.ButtonBox.ButtonBoxChild w35 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnLeft [this.btnStandardMetric]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbtnLeft.Gtk.ButtonBox+ButtonBoxChild
			this.btnMetric = new global::Gtk.Button ();
			this.btnMetric.WidthRequest = 112;
			this.btnMetric.HeightRequest = 40;
			this.btnMetric.CanFocus = true;
			this.btnMetric.Name = "btnMetric";
			this.btnMetric.UseUnderline = true;
			this.btnMetric.BorderWidth = ((uint)(4));
			this.btnMetric.Label = global::Mono.Unix.Catalog.GetString ("Metric");
			this.vbtnLeft.Add (this.btnMetric);
			global::Gtk.ButtonBox.ButtonBoxChild w36 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnLeft [this.btnMetric]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.hbox8.Add (this.vbtnLeft);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbtnLeft]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.hbox8.Add (this.alignment6);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.alignment6]));
			w38.Position = 2;
			this.hbox7.Add (this.hbox8);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox8]));
			w39.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.hbox9.Add (this.alignment7);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment7]));
			w40.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbtnCenter = new global::Gtk.VButtonBox ();
			this.vbtnCenter.WidthRequest = 142;
			this.vbtnCenter.HeightRequest = 142;
			this.vbtnCenter.Name = "vbtnCenter";
			this.vbtnCenter.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbtnCenter.Gtk.ButtonBox+ButtonBoxChild
			this.btnSolve = new global::Gtk.Button ();
			this.btnSolve.WidthRequest = 112;
			this.btnSolve.HeightRequest = 40;
			this.btnSolve.CanFocus = true;
			this.btnSolve.Name = "btnSolve";
			this.btnSolve.UseUnderline = true;
			this.btnSolve.BorderWidth = ((uint)(4));
			this.btnSolve.Label = global::Mono.Unix.Catalog.GetString ("Solve");
			this.vbtnCenter.Add (this.btnSolve);
			global::Gtk.ButtonBox.ButtonBoxChild w41 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnCenter [this.btnSolve]));
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbtnCenter.Gtk.ButtonBox+ButtonBoxChild
			this.btnStore = new global::Gtk.Button ();
			this.btnStore.WidthRequest = 112;
			this.btnStore.HeightRequest = 40;
			this.btnStore.CanFocus = true;
			this.btnStore.Name = "btnStore";
			this.btnStore.UseUnderline = true;
			this.btnStore.BorderWidth = ((uint)(4));
			this.btnStore.Label = global::Mono.Unix.Catalog.GetString ("Store Result");
			this.vbtnCenter.Add (this.btnStore);
			global::Gtk.ButtonBox.ButtonBoxChild w42 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnCenter [this.btnStore]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			// Container child vbtnCenter.Gtk.ButtonBox+ButtonBoxChild
			this.btnDisplayStore = new global::Gtk.Button ();
			this.btnDisplayStore.WidthRequest = 112;
			this.btnDisplayStore.HeightRequest = 40;
			this.btnDisplayStore.CanFocus = true;
			this.btnDisplayStore.Name = "btnDisplayStore";
			this.btnDisplayStore.UseUnderline = true;
			this.btnDisplayStore.BorderWidth = ((uint)(4));
			this.btnDisplayStore.Label = global::Mono.Unix.Catalog.GetString ("Display Store");
			this.vbtnCenter.Add (this.btnDisplayStore);
			global::Gtk.ButtonBox.ButtonBoxChild w43 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnCenter [this.btnDisplayStore]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbtnCenter.Gtk.ButtonBox+ButtonBoxChild
			this.btnClearStore = new global::Gtk.Button ();
			this.btnClearStore.WidthRequest = 112;
			this.btnClearStore.HeightRequest = 40;
			this.btnClearStore.CanFocus = true;
			this.btnClearStore.Name = "btnClearStore";
			this.btnClearStore.UseUnderline = true;
			this.btnClearStore.BorderWidth = ((uint)(4));
			this.btnClearStore.Label = global::Mono.Unix.Catalog.GetString ("Clear Store");
			this.vbtnCenter.Add (this.btnClearStore);
			global::Gtk.ButtonBox.ButtonBoxChild w44 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnCenter [this.btnClearStore]));
			w44.Position = 3;
			w44.Expand = false;
			w44.Fill = false;
			this.hbox9.Add (this.vbtnCenter);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbtnCenter]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.hbox9.Add (this.alignment8);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment8]));
			w46.Position = 2;
			this.hbox7.Add (this.hbox9);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox9]));
			w47.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.hbox10.Add (this.alignment9);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.alignment9]));
			w48.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbtnRight = new global::Gtk.VButtonBox ();
			this.vbtnRight.WidthRequest = 142;
			this.vbtnRight.HeightRequest = 142;
			this.vbtnRight.Name = "vbtnRight";
			this.vbtnRight.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbtnRight.Gtk.ButtonBox+ButtonBoxChild
			this.btnPrintForm = new global::Gtk.Button ();
			this.btnPrintForm.WidthRequest = 112;
			this.btnPrintForm.HeightRequest = 40;
			this.btnPrintForm.CanFocus = true;
			this.btnPrintForm.Name = "btnPrintForm";
			this.btnPrintForm.UseUnderline = true;
			this.btnPrintForm.BorderWidth = ((uint)(4));
			this.btnPrintForm.Label = global::Mono.Unix.Catalog.GetString ("Print Form");
			this.vbtnRight.Add (this.btnPrintForm);
			global::Gtk.ButtonBox.ButtonBoxChild w49 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnRight [this.btnPrintForm]));
			w49.Expand = false;
			w49.Fill = false;
			// Container child vbtnRight.Gtk.ButtonBox+ButtonBoxChild
			this.btnPrintStored = new global::Gtk.Button ();
			this.btnPrintStored.WidthRequest = 112;
			this.btnPrintStored.HeightRequest = 40;
			this.btnPrintStored.CanFocus = true;
			this.btnPrintStored.Name = "btnPrintStored";
			this.btnPrintStored.UseUnderline = true;
			this.btnPrintStored.BorderWidth = ((uint)(4));
			this.btnPrintStored.Label = global::Mono.Unix.Catalog.GetString ("Print Stored");
			this.vbtnRight.Add (this.btnPrintStored);
			global::Gtk.ButtonBox.ButtonBoxChild w50 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnRight [this.btnPrintStored]));
			w50.Position = 1;
			w50.Expand = false;
			w50.Fill = false;
			// Container child vbtnRight.Gtk.ButtonBox+ButtonBoxChild
			this.btnSaveForm = new global::Gtk.Button ();
			this.btnSaveForm.WidthRequest = 112;
			this.btnSaveForm.HeightRequest = 40;
			this.btnSaveForm.CanFocus = true;
			this.btnSaveForm.Name = "btnSaveForm";
			this.btnSaveForm.UseUnderline = true;
			this.btnSaveForm.BorderWidth = ((uint)(4));
			this.btnSaveForm.Label = global::Mono.Unix.Catalog.GetString ("Save Form");
			this.vbtnRight.Add (this.btnSaveForm);
			global::Gtk.ButtonBox.ButtonBoxChild w51 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnRight [this.btnSaveForm]));
			w51.Position = 2;
			w51.Expand = false;
			w51.Fill = false;
			// Container child vbtnRight.Gtk.ButtonBox+ButtonBoxChild
			this.btnClose = new global::Gtk.Button ();
			this.btnClose.WidthRequest = 112;
			this.btnClose.HeightRequest = 40;
			this.btnClose.CanFocus = true;
			this.btnClose.Name = "btnClose";
			this.btnClose.UseStock = true;
			this.btnClose.UseUnderline = true;
			this.btnClose.BorderWidth = ((uint)(4));
			this.btnClose.Label = "gtk-close";
			this.vbtnRight.Add (this.btnClose);
			global::Gtk.ButtonBox.ButtonBoxChild w52 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtnRight [this.btnClose]));
			w52.Position = 3;
			w52.Expand = false;
			w52.Fill = false;
			this.hbox10.Add (this.vbtnRight);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbtnRight]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			this.hbox10.Add (this.alignment10);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.alignment10]));
			w54.Position = 2;
			this.hbox7.Add (this.hbox10);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox10]));
			w55.Position = 2;
			this.dialog1_VBox.Add (this.hbox7);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.hbox7]));
			w56.Position = 2;
			this.Add (this.dialog1_VBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			this.lblEnter1.Hide ();
			this.lblEnter2.Hide ();
			this.lblEnter3.Hide ();
			this.lblFeet.Hide ();
			this.lblInches.Hide ();
			this.lblYards.Hide ();
			this.txtBoxFeet1.Hide ();
			this.txtBoxFeet2.Hide ();
			this.txtBoxFeet3.Hide ();
			this.txtBoxInches1.Hide ();
			this.txtBoxInches2.Hide ();
			this.txtBoxInches3.Hide ();
			this.txtBoxYard1.Hide ();
			this.txtBoxYard2.Hide ();
			this.txtBoxYard3.Hide ();
			this.lblCubicFeet.Hide ();
			this.lblCubicInches.Hide ();
			this.lblCubicYards.Hide ();
			this.Show ();
			this.btnClear.Clicked += new global::System.EventHandler (this.OnBtnClearFormClicked);
			this.btnStandardMetric.Clicked += new global::System.EventHandler (this.OnBtnStandardClicked);
			this.btnMetric.Clicked += new global::System.EventHandler (this.OnBtnMetricClicked);
			this.btnSolve.Clicked += new global::System.EventHandler (this.OnBtnSolveClicked);
			this.btnStore.Clicked += new global::System.EventHandler (this.OnBtnStoreResultClicked);
			this.btnDisplayStore.Clicked += new global::System.EventHandler (this.OnBtnDisplayStoredClicked);
			this.btnClearStore.Clicked += new global::System.EventHandler (this.OnBtnClearStoredClicked);
			this.btnPrintForm.Clicked += new global::System.EventHandler (this.OnBtnPrintFormClicked);
			this.btnPrintStored.Clicked += new global::System.EventHandler (this.OnBtnPrintStoredClicked);
			this.btnSaveForm.Clicked += new global::System.EventHandler (this.OnBtnSaveFormClicked);
			this.btnClose.Clicked += new global::System.EventHandler (this.OnBtnClose);
		}
	}
}
