
// This file has been generated by the GUI designer. Do not modify.
namespace BuildingFormulas
{
	public partial class HexagonCylinderVolume
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BuildingFormulas.HexagonCylinderVolume
			this.Name = "BuildingFormulas.HexagonCylinderVolume";
			this.Title = global::Mono.Unix.Catalog.GetString ("HexagonCylinderVolume");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
