
// This file has been generated by the GUI designer. Do not modify.

public partial class dlgDisplayTagData
{
	private global::Gtk.VBox vbox4;
	private global::Gtk.Alignment aliTop;
	private global::Gtk.Label lblInfo;
	private global::Gtk.Alignment alilblInfoTable;
	private global::Gtk.Table tblTag;
	private global::Gtk.Label lblAlbum;
	private global::Gtk.Label lblAlbumArt;
	private global::Gtk.Label lblArtist;
	private global::Gtk.Label lblDiscCount;
	private global::Gtk.Label lblDiscNum;
	private global::Gtk.Label lblGenre;
	private global::Gtk.Label lblSong;
	private global::Gtk.Label lblTrackCount;
	private global::Gtk.Label lblTrackNum;
	private global::Gtk.Label lblYear;
	private global::Gtk.Entry txtAlbum;
	private global::Gtk.Entry txtAlbumArt;
	private global::Gtk.Entry txtArtist;
	private global::Gtk.Entry txtDiscCount;
	private global::Gtk.Entry txtDiscNum;
	private global::Gtk.Entry txtGenre;
	private global::Gtk.Entry txtSong;
	private global::Gtk.Entry txtTrackCount;
	private global::Gtk.Entry txtTrackNum;
	private global::Gtk.Entry txtYear;
	private global::Gtk.Alignment aliTablelblSongPath;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label lblSongPath;
	private global::Gtk.Alignment aliBetweenlblPathLblSngPath;
	private global::Gtk.Label lblSngPath;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label lblArtistPath;
	private global::Gtk.Alignment aliBetweenlblArtistPathlblArtPat;
	private global::Gtk.Label lblArtPath;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label lblAlbumPath;
	private global::Gtk.Alignment aliBetweenlblAlbumPathlblAlbPath;
	private global::Gtk.Label lblAlbPath;
	private global::Gtk.Alignment aliBetweenlblAlbumbtnData;
	private global::Gtk.HButtonBox hbtnData;
	private global::Gtk.Button btnFirst;
	private global::Gtk.Button btnPrevious;
	private global::Gtk.Button btnNext;
	private global::Gtk.Button btnLast;
	private global::Gtk.Button btnEdit;
	private global::Gtk.Button btnCancel;
	private global::Gtk.Button btnUpdate;
	private global::Gtk.Button buttonCancel;
	private global::Gtk.Button buttonOk;
    
	protected virtual void Build ()
	{
		
	
		// Container child dialog1_VBox.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 10;
		// Container child vbox4.Gtk.Box+BoxChild
		this.aliTop = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliTop.HeightRequest = 20;
		this.aliTop.Name = "aliTop";
		this.vbox4.Add (this.aliTop);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.aliTop]));
		w2.Position = 0;
		w2.Expand = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.lblInfo = new global::Gtk.Label ();
		this.lblInfo.WidthRequest = 1023;
		this.lblInfo.HeightRequest = 24;
		this.lblInfo.Name = "lblInfo";
		this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("lblInfo");
		this.vbox4.Add (this.lblInfo);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblInfo]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.alilblInfoTable = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alilblInfoTable.HeightRequest = 20;
		this.alilblInfoTable.Name = "alilblInfoTable";
		this.vbox4.Add (this.alilblInfoTable);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.alilblInfoTable]));
		w4.Position = 2;
		w4.Expand = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.tblTag = new global::Gtk.Table (((uint)(5)), ((uint)(4)), false);
		this.tblTag.Name = "tblTag";
		this.tblTag.RowSpacing = ((uint)(20));
		this.tblTag.ColumnSpacing = ((uint)(10));
		this.tblTag.BorderWidth = ((uint)(2));
		// Container child tblTag.Gtk.Table+TableChild
		this.lblAlbum = new global::Gtk.Label ();
		this.lblAlbum.WidthRequest = 175;
		this.lblAlbum.HeightRequest = 24;
		this.lblAlbum.Name = "lblAlbum";
		this.lblAlbum.LabelProp = global::Mono.Unix.Catalog.GetString ("Album Name:");
		this.lblAlbum.Justify = ((global::Gtk.Justification)(2));
		this.lblAlbum.SingleLineMode = true;
		this.tblTag.Add (this.lblAlbum);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblAlbum]));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.lblAlbumArt = new global::Gtk.Label ();
		this.lblAlbumArt.Name = "lblAlbumArt";
		this.lblAlbumArt.LabelProp = global::Mono.Unix.Catalog.GetString ("Album Art Count:");
		this.lblAlbumArt.Justify = ((global::Gtk.Justification)(2));
		this.lblAlbumArt.SingleLineMode = true;
		this.tblTag.Add (this.lblAlbumArt);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblAlbumArt]));
		w6.TopAttach = ((uint)(3));
		w6.BottomAttach = ((uint)(4));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.lblArtist = new global::Gtk.Label ();
		this.lblArtist.WidthRequest = 175;
		this.lblArtist.HeightRequest = 24;
		this.lblArtist.Name = "lblArtist";
		this.lblArtist.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist Name:");
		this.lblArtist.Justify = ((global::Gtk.Justification)(2));
		this.lblArtist.SingleLineMode = true;
		this.tblTag.Add (this.lblArtist);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblArtist]));
		w7.XOptions = ((global::Gtk.AttachOptions)(0));
		w7.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child tblTag.Gtk.Table+TableChild
		this.lblDiscCount = new global::Gtk.Label ();
		this.lblDiscCount.Name = "lblDiscCount";
		this.lblDiscCount.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Discs:");
		this.lblDiscCount.SingleLineMode = true;
		this.tblTag.Add (this.lblDiscCount);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblDiscCount]));
		w8.TopAttach = ((uint)(4));
		w8.BottomAttach = ((uint)(5));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.lblDiscNum = new global::Gtk.Label ();
		this.lblDiscNum.Name = "lblDiscNum";
		this.lblDiscNum.LabelProp = global::Mono.Unix.Catalog.GetString ("Disc Number:");
		this.lblDiscNum.SingleLineMode = true;
		this.tblTag.Add (this.lblDiscNum);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblDiscNum]));
		w9.TopAttach = ((uint)(4));
		w9.BottomAttach = ((uint)(5));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.lblGenre = new global::Gtk.Label ();
		this.lblGenre.Name = "lblGenre";
		this.lblGenre.LabelProp = global::Mono.Unix.Catalog.GetString ("Genre:");
		this.lblGenre.Justify = ((global::Gtk.Justification)(2));
		this.lblGenre.SingleLineMode = true;
		this.tblTag.Add (this.lblGenre);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblGenre]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.LeftAttach = ((uint)(2));
		w10.RightAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.lblSong = new global::Gtk.Label ();
		this.lblSong.Name = "lblSong";
		this.lblSong.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Title:");
		this.lblSong.Justify = ((global::Gtk.Justification)(2));
		this.lblSong.SingleLineMode = true;
		this.tblTag.Add (this.lblSong);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblSong]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.lblTrackCount = new global::Gtk.Label ();
		this.lblTrackCount.Name = "lblTrackCount";
		this.lblTrackCount.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Tracks:");
		this.lblTrackCount.Justify = ((global::Gtk.Justification)(2));
		this.lblTrackCount.SingleLineMode = true;
		this.tblTag.Add (this.lblTrackCount);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblTrackCount]));
		w12.TopAttach = ((uint)(2));
		w12.BottomAttach = ((uint)(3));
		w12.LeftAttach = ((uint)(2));
		w12.RightAttach = ((uint)(3));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.lblTrackNum = new global::Gtk.Label ();
		this.lblTrackNum.Name = "lblTrackNum";
		this.lblTrackNum.LabelProp = global::Mono.Unix.Catalog.GetString ("Track Number:");
		this.lblTrackNum.Justify = ((global::Gtk.Justification)(2));
		this.lblTrackNum.SingleLineMode = true;
		this.tblTag.Add (this.lblTrackNum);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblTrackNum]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.lblYear = new global::Gtk.Label ();
		this.lblYear.Name = "lblYear";
		this.lblYear.LabelProp = global::Mono.Unix.Catalog.GetString ("Year:");
		this.lblYear.SingleLineMode = true;
		this.tblTag.Add (this.lblYear);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblYear]));
		w14.TopAttach = ((uint)(3));
		w14.BottomAttach = ((uint)(4));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.txtAlbum = new global::Gtk.Entry ();
		this.txtAlbum.WidthRequest = 315;
		this.txtAlbum.HeightRequest = 24;
		this.txtAlbum.CanFocus = true;
		this.txtAlbum.Name = "txtAlbum";
		this.txtAlbum.Text = global::Mono.Unix.Catalog.GetString ("txtAlbum");
		this.txtAlbum.IsEditable = true;
		this.txtAlbum.InvisibleChar = '•';
		this.tblTag.Add (this.txtAlbum);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtAlbum]));
		w15.LeftAttach = ((uint)(3));
		w15.RightAttach = ((uint)(4));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child tblTag.Gtk.Table+TableChild
		this.txtAlbumArt = new global::Gtk.Entry ();
		this.txtAlbumArt.CanFocus = true;
		this.txtAlbumArt.Name = "txtAlbumArt";
		this.txtAlbumArt.Text = global::Mono.Unix.Catalog.GetString ("txtAlbumArt");
		this.txtAlbumArt.IsEditable = true;
		this.txtAlbumArt.InvisibleChar = '•';
		this.tblTag.Add (this.txtAlbumArt);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtAlbumArt]));
		w16.TopAttach = ((uint)(3));
		w16.BottomAttach = ((uint)(4));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.txtArtist = new global::Gtk.Entry ();
		this.txtArtist.WidthRequest = 315;
		this.txtArtist.HeightRequest = 24;
		this.txtArtist.CanFocus = true;
		this.txtArtist.Name = "txtArtist";
		this.txtArtist.Text = global::Mono.Unix.Catalog.GetString ("txtArtist");
		this.txtArtist.IsEditable = true;
		this.txtArtist.InvisibleChar = '•';
		this.tblTag.Add (this.txtArtist);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtArtist]));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child tblTag.Gtk.Table+TableChild
		this.txtDiscCount = new global::Gtk.Entry ();
		this.txtDiscCount.CanFocus = true;
		this.txtDiscCount.Name = "txtDiscCount";
		this.txtDiscCount.Text = global::Mono.Unix.Catalog.GetString ("txtDiscCount");
		this.txtDiscCount.IsEditable = true;
		this.txtDiscCount.InvisibleChar = '•';
		this.tblTag.Add (this.txtDiscCount);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtDiscCount]));
		w18.TopAttach = ((uint)(4));
		w18.BottomAttach = ((uint)(5));
		w18.LeftAttach = ((uint)(3));
		w18.RightAttach = ((uint)(4));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.txtDiscNum = new global::Gtk.Entry ();
		this.txtDiscNum.CanFocus = true;
		this.txtDiscNum.Name = "txtDiscNum";
		this.txtDiscNum.Text = global::Mono.Unix.Catalog.GetString ("txtDiscNum");
		this.txtDiscNum.IsEditable = true;
		this.txtDiscNum.InvisibleChar = '•';
		this.tblTag.Add (this.txtDiscNum);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtDiscNum]));
		w19.TopAttach = ((uint)(4));
		w19.BottomAttach = ((uint)(5));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.txtGenre = new global::Gtk.Entry ();
		this.txtGenre.CanFocus = true;
		this.txtGenre.Name = "txtGenre";
		this.txtGenre.Text = global::Mono.Unix.Catalog.GetString ("txtGenre");
		this.txtGenre.IsEditable = true;
		this.txtGenre.InvisibleChar = '•';
		this.tblTag.Add (this.txtGenre);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtGenre]));
		w20.TopAttach = ((uint)(1));
		w20.BottomAttach = ((uint)(2));
		w20.LeftAttach = ((uint)(3));
		w20.RightAttach = ((uint)(4));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.txtSong = new global::Gtk.Entry ();
		this.txtSong.CanFocus = true;
		this.txtSong.Name = "txtSong";
		this.txtSong.Text = global::Mono.Unix.Catalog.GetString ("txtSong");
		this.txtSong.IsEditable = true;
		this.txtSong.InvisibleChar = '•';
		this.tblTag.Add (this.txtSong);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtSong]));
		w21.TopAttach = ((uint)(1));
		w21.BottomAttach = ((uint)(2));
		w21.LeftAttach = ((uint)(1));
		w21.RightAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.txtTrackCount = new global::Gtk.Entry ();
		this.txtTrackCount.CanFocus = true;
		this.txtTrackCount.Name = "txtTrackCount";
		this.txtTrackCount.Text = global::Mono.Unix.Catalog.GetString ("txtTrackCount");
		this.txtTrackCount.IsEditable = true;
		this.txtTrackCount.InvisibleChar = '•';
		this.tblTag.Add (this.txtTrackCount);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtTrackCount]));
		w22.TopAttach = ((uint)(2));
		w22.BottomAttach = ((uint)(3));
		w22.LeftAttach = ((uint)(3));
		w22.RightAttach = ((uint)(4));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.txtTrackNum = new global::Gtk.Entry ();
		this.txtTrackNum.CanFocus = true;
		this.txtTrackNum.Name = "txtTrackNum";
		this.txtTrackNum.Text = global::Mono.Unix.Catalog.GetString ("txtTrackNum");
		this.txtTrackNum.IsEditable = true;
		this.txtTrackNum.InvisibleChar = '•';
		this.tblTag.Add (this.txtTrackNum);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtTrackNum]));
		w23.TopAttach = ((uint)(2));
		w23.BottomAttach = ((uint)(3));
		w23.LeftAttach = ((uint)(1));
		w23.RightAttach = ((uint)(2));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblTag.Gtk.Table+TableChild
		this.txtYear = new global::Gtk.Entry ();
		this.txtYear.CanFocus = true;
		this.txtYear.Name = "txtYear";
		this.txtYear.Text = global::Mono.Unix.Catalog.GetString ("txtYear");
		this.txtYear.IsEditable = true;
		this.txtYear.InvisibleChar = '•';
		this.tblTag.Add (this.txtYear);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtYear]));
		w24.TopAttach = ((uint)(3));
		w24.BottomAttach = ((uint)(4));
		w24.LeftAttach = ((uint)(3));
		w24.RightAttach = ((uint)(4));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox4.Add (this.tblTag);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.tblTag]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.aliTablelblSongPath = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliTablelblSongPath.HeightRequest = 20;
		this.aliTablelblSongPath.Name = "aliTablelblSongPath";
		this.vbox4.Add (this.aliTablelblSongPath);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.aliTablelblSongPath]));
		w26.Position = 4;
		w26.Expand = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lblSongPath = new global::Gtk.Label ();
		this.lblSongPath.WidthRequest = 175;
		this.lblSongPath.HeightRequest = 24;
		this.lblSongPath.Name = "lblSongPath";
		this.lblSongPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Path:");
		this.hbox1.Add (this.lblSongPath);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblSongPath]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.aliBetweenlblPathLblSngPath = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliBetweenlblPathLblSngPath.WidthRequest = 10;
		this.aliBetweenlblPathLblSngPath.HeightRequest = 24;
		this.aliBetweenlblPathLblSngPath.Name = "aliBetweenlblPathLblSngPath";
		this.hbox1.Add (this.aliBetweenlblPathLblSngPath);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.aliBetweenlblPathLblSngPath]));
		w28.Position = 1;
		w28.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lblSngPath = new global::Gtk.Label ();
		this.lblSngPath.WidthRequest = 810;
		this.lblSngPath.HeightRequest = 24;
		this.lblSngPath.Name = "lblSngPath";
		this.lblSngPath.LabelProp = global::Mono.Unix.Catalog.GetString ("lblSngPath");
		this.hbox1.Add (this.lblSngPath);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblSngPath]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.vbox4.Add (this.hbox1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
		w30.Position = 5;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.lblArtistPath = new global::Gtk.Label ();
		this.lblArtistPath.WidthRequest = 175;
		this.lblArtistPath.HeightRequest = 24;
		this.lblArtistPath.Name = "lblArtistPath";
		this.lblArtistPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist Folder Path:");
		this.lblArtistPath.Justify = ((global::Gtk.Justification)(2));
		this.hbox2.Add (this.lblArtistPath);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblArtistPath]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.aliBetweenlblArtistPathlblArtPat = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliBetweenlblArtistPathlblArtPat.WidthRequest = 10;
		this.aliBetweenlblArtistPathlblArtPat.HeightRequest = 24;
		this.aliBetweenlblArtistPathlblArtPat.Name = "aliBetweenlblArtistPathlblArtPat";
		this.hbox2.Add (this.aliBetweenlblArtistPathlblArtPat);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.aliBetweenlblArtistPathlblArtPat]));
		w32.Position = 1;
		w32.Expand = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.lblArtPath = new global::Gtk.Label ();
		this.lblArtPath.WidthRequest = 810;
		this.lblArtPath.Name = "lblArtPath";
		this.lblArtPath.LabelProp = global::Mono.Unix.Catalog.GetString ("lblArtPath");
		this.hbox2.Add (this.lblArtPath);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblArtPath]));
		w33.Position = 2;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox4.Add (this.hbox2);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
		w34.Position = 6;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lblAlbumPath = new global::Gtk.Label ();
		this.lblAlbumPath.WidthRequest = 175;
		this.lblAlbumPath.HeightRequest = 24;
		this.lblAlbumPath.Name = "lblAlbumPath";
		this.lblAlbumPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Album Folder Path:");
		this.hbox3.Add (this.lblAlbumPath);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblAlbumPath]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.aliBetweenlblAlbumPathlblAlbPath = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliBetweenlblAlbumPathlblAlbPath.WidthRequest = 10;
		this.aliBetweenlblAlbumPathlblAlbPath.HeightRequest = 24;
		this.aliBetweenlblAlbumPathlblAlbPath.Name = "aliBetweenlblAlbumPathlblAlbPath";
		this.hbox3.Add (this.aliBetweenlblAlbumPathlblAlbPath);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.aliBetweenlblAlbumPathlblAlbPath]));
		w36.Position = 1;
		w36.Expand = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lblAlbPath = new global::Gtk.Label ();
		this.lblAlbPath.WidthRequest = 810;
		this.lblAlbPath.HeightRequest = 24;
		this.lblAlbPath.Name = "lblAlbPath";
		this.lblAlbPath.LabelProp = global::Mono.Unix.Catalog.GetString ("lblAlbPath");
		this.hbox3.Add (this.lblAlbPath);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblAlbPath]));
		w37.Position = 2;
		w37.Expand = false;
		w37.Fill = false;
		this.vbox4.Add (this.hbox3);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
		w38.Position = 7;
		w38.Expand = false;
		w38.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.aliBetweenlblAlbumbtnData = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliBetweenlblAlbumbtnData.HeightRequest = 20;
		this.aliBetweenlblAlbumbtnData.Name = "aliBetweenlblAlbumbtnData";
		this.vbox4.Add (this.aliBetweenlblAlbumbtnData);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.aliBetweenlblAlbumbtnData]));
		w39.Position = 8;
		w39.Expand = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbtnData = new global::Gtk.HButtonBox ();
		this.hbtnData.HeightRequest = 40;
		this.hbtnData.Name = "hbtnData";
		this.hbtnData.BorderWidth = ((uint)(2));
		// Container child hbtnData.Gtk.ButtonBox+ButtonBoxChild
		this.btnFirst = new global::Gtk.Button ();
		this.btnFirst.CanFocus = true;
		this.btnFirst.Name = "btnFirst";
		this.btnFirst.UseUnderline = true;
		this.btnFirst.BorderWidth = ((uint)(2));
		// Container child btnFirst.Gtk.Container+ContainerChild
		global::Gtk.Alignment w40 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w41 = new global::Gtk.HBox ();
		w41.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w42 = new global::Gtk.Image ();
	
		w41.Add (w42);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w44 = new global::Gtk.Label ();
		w44.LabelProp = global::Mono.Unix.Catalog.GetString ("Move First");
		w44.UseUnderline = true;
		w41.Add (w44);
		w40.Add (w41);
		this.btnFirst.Add (w40);
		this.hbtnData.Add (this.btnFirst);
		global::Gtk.ButtonBox.ButtonBoxChild w48 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnData [this.btnFirst]));
		w48.Expand = false;
		w48.Fill = false;
		// Container child hbtnData.Gtk.ButtonBox+ButtonBoxChild
		this.btnPrevious = new global::Gtk.Button ();
		this.btnPrevious.CanFocus = true;
		this.btnPrevious.Name = "btnPrevious";
		this.btnPrevious.UseUnderline = true;
		this.btnPrevious.BorderWidth = ((uint)(2));
		// Container child btnPrevious.Gtk.Container+ContainerChild
		global::Gtk.Alignment w49 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w50 = new global::Gtk.HBox ();
		w50.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w51 = new global::Gtk.Image ();
		
		w50.Add (w51);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w53 = new global::Gtk.Label ();
		w53.LabelProp = global::Mono.Unix.Catalog.GetString ("Move Previous");
		w53.UseUnderline = true;
		w50.Add (w53);
		w49.Add (w50);
		this.btnPrevious.Add (w49);
		this.hbtnData.Add (this.btnPrevious);
		global::Gtk.ButtonBox.ButtonBoxChild w57 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnData [this.btnPrevious]));
		w57.Position = 1;
		w57.Expand = false;
		w57.Fill = false;
		// Container child hbtnData.Gtk.ButtonBox+ButtonBoxChild
		this.btnNext = new global::Gtk.Button ();
		this.btnNext.CanFocus = true;
		this.btnNext.Name = "btnNext";
		this.btnNext.UseUnderline = true;
		// Container child btnNext.Gtk.Container+ContainerChild
		global::Gtk.Alignment w58 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w59 = new global::Gtk.HBox ();
		w59.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w60 = new global::Gtk.Image ();
		
		w59.Add (w60);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w62 = new global::Gtk.Label ();
		w62.LabelProp = global::Mono.Unix.Catalog.GetString ("Move Next");
		w62.UseUnderline = true;
		w59.Add (w62);
		w58.Add (w59);
		this.btnNext.Add (w58);
		this.hbtnData.Add (this.btnNext);
		global::Gtk.ButtonBox.ButtonBoxChild w66 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnData [this.btnNext]));
		w66.Position = 2;
		w66.Expand = false;
		w66.Fill = false;
		// Container child hbtnData.Gtk.ButtonBox+ButtonBoxChild
		this.btnLast = new global::Gtk.Button ();
		this.btnLast.CanFocus = true;
		this.btnLast.Name = "btnLast";
		this.btnLast.UseUnderline = true;
		// Container child btnLast.Gtk.Container+ContainerChild
		global::Gtk.Alignment w67 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w68 = new global::Gtk.HBox ();
		w68.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w69 = new global::Gtk.Image ();
		
		w68.Add (w69);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w71 = new global::Gtk.Label ();
		w71.LabelProp = global::Mono.Unix.Catalog.GetString ("Move Last");
		w71.UseUnderline = true;
		w68.Add (w71);
		w67.Add (w68);
		this.btnLast.Add (w67);
		this.hbtnData.Add (this.btnLast);
		global::Gtk.ButtonBox.ButtonBoxChild w75 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnData [this.btnLast]));
		w75.Position = 3;
		w75.Expand = false;
		w75.Fill = false;
		// Container child hbtnData.Gtk.ButtonBox+ButtonBoxChild
		this.btnEdit = new global::Gtk.Button ();
		this.btnEdit.CanFocus = true;
		this.btnEdit.Name = "btnEdit";
		this.btnEdit.UseUnderline = true;
		// Container child btnEdit.Gtk.Container+ContainerChild
		global::Gtk.Alignment w76 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w77 = new global::Gtk.HBox ();
		w77.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w78 = new global::Gtk.Image ();
		
		w77.Add (w78);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w80 = new global::Gtk.Label ();
		w80.LabelProp = global::Mono.Unix.Catalog.GetString ("Edit Record");
		w80.UseUnderline = true;
		w77.Add (w80);
		w76.Add (w77);
		this.btnEdit.Add (w76);
		this.hbtnData.Add (this.btnEdit);
		global::Gtk.ButtonBox.ButtonBoxChild w84 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnData [this.btnEdit]));
		w84.Position = 4;
		w84.Expand = false;
		w84.Fill = false;
		// Container child hbtnData.Gtk.ButtonBox+ButtonBoxChild
		this.btnCancel = new global::Gtk.Button ();
		this.btnCancel.CanFocus = true;
		this.btnCancel.Name = "btnCancel";
		this.btnCancel.UseUnderline = true;
		// Container child btnCancel.Gtk.Container+ContainerChild
		global::Gtk.Alignment w85 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w86 = new global::Gtk.HBox ();
		w86.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w87 = new global::Gtk.Image ();
		
		w86.Add (w87);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w89 = new global::Gtk.Label ();
		w89.LabelProp = global::Mono.Unix.Catalog.GetString ("Cancel Changes");
		w89.UseUnderline = true;
		w86.Add (w89);
		w85.Add (w86);
		this.btnCancel.Add (w85);
		this.hbtnData.Add (this.btnCancel);
		global::Gtk.ButtonBox.ButtonBoxChild w93 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnData [this.btnCancel]));
		w93.Position = 5;
		w93.Expand = false;
		w93.Fill = false;
		// Container child hbtnData.Gtk.ButtonBox+ButtonBoxChild
		this.btnUpdate = new global::Gtk.Button ();
		this.btnUpdate.CanFocus = true;
		this.btnUpdate.Name = "btnUpdate";
		this.btnUpdate.UseUnderline = true;
		// Container child btnUpdate.Gtk.Container+ContainerChild
		global::Gtk.Alignment w94 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w95 = new global::Gtk.HBox ();
		w95.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w96 = new global::Gtk.Image ();
		
		w95.Add (w96);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w98 = new global::Gtk.Label ();
		w98.LabelProp = global::Mono.Unix.Catalog.GetString ("Update Record");
		w98.UseUnderline = true;
		w95.Add (w98);
		w94.Add (w95);
		this.btnUpdate.Add (w94);
		this.hbtnData.Add (this.btnUpdate);
		global::Gtk.ButtonBox.ButtonBoxChild w102 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnData [this.btnUpdate]));
		w102.Position = 6;
		w102.Expand = false;
		w102.Fill = false;
		this.vbox4.Add (this.hbtnData);
		global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbtnData]));
		w103.Position = 9;
		w103.Expand = false;
		w103.Fill = false;
		
	
		
		// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.buttonCancel = new global::Gtk.Button ();
		this.buttonCancel.CanDefault = true;
		this.buttonCancel.CanFocus = true;
		this.buttonCancel.Name = "buttonCancel";
		this.buttonCancel.UseStock = true;
		this.buttonCancel.UseUnderline = true;
		this.buttonCancel.Label = "gtk-cancel";
	
		
		// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.buttonOk = new global::Gtk.Button ();
		this.buttonOk.CanDefault = true;
		this.buttonOk.CanFocus = true;
		this.buttonOk.Name = "buttonOk";
		this.buttonOk.UseStock = true;
		this.buttonOk.UseUnderline = true;
		this.buttonOk.Label = "gtk-ok";
	
		
	
		
	}
}
