
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action UserInformationAction;
	private global::Gtk.Action mnuMain_UserInfo_MusicPath;
	private global::Gtk.Action PathActionsAction;
	private global::Gtk.Action CreateVariousArtistFolderAction;
	private global::Gtk.Action TagActionsAction;
	private global::Gtk.Action CheckAllSongTagsAction;
	private global::Gtk.Action QuitApplicationAction;
	private global::Gtk.Action mnuReplaceSpaceUnderscore;
	private global::Gtk.Action mnuReplaceUnderscore;
	private global::Gtk.Action mnuCreateArtistFolder;
	private global::Gtk.Action mnuShowSngTagWin;
	private global::Gtk.Action mnuQuit;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action mnuQuitApp;
	private global::Gtk.Action mnuLoadSongs;
	private global::Gtk.Action mnuMusicPath;
	private global::Gtk.Action MusicDirectoryStructureAction;
	private global::Gtk.Action mnuMusicPath1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar mnuMain;
	private global::Gtk.Alignment aliMenuLabelInfo;
	private global::Gtk.Label lblInfo;
	private global::Gtk.Alignment aliLblInfo_TableUserInfo;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Alignment aliLeft_TableUser;
	private global::Gtk.Table tblUserInfo;
	private global::Gtk.Alignment aliLeft_UserHome;
	private global::Gtk.Alignment aliLeft_UserName;
	private global::Gtk.Alignment aliRight_LblUserName;
	private global::Gtk.Alignment aliRight_UserHomePath;
	private global::Gtk.Label lblUser;
	private global::Gtk.Label lblUserHome;
	private global::Gtk.Label lblUserHomePath;
	private global::Gtk.Label lblUserMusic;
	private global::Gtk.Label lblUserMusicPath;
	private global::Gtk.Label lblUserName;
	private global::Gtk.Alignment aliRigth_TableUserInfo;
	private global::Gtk.Alignment aliBottom_TableUser;
	private global::Gtk.Alignment aliAbove_ButtonBox;
	private global::Gtk.HButtonBox btnBox_Bottom;
	private global::Gtk.Button btnQuit;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.UserInformationAction = new global::Gtk.Action ("UserInformationAction", global::Mono.Unix.Catalog.GetString ("User Information"), null, null);
		this.UserInformationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("User Information");
		w1.Add (this.UserInformationAction, null);
		this.mnuMain_UserInfo_MusicPath = new global::Gtk.Action ("mnuMain_UserInfo_MusicPath", global::Mono.Unix.Catalog.GetString ("Select Music Path"), null, null);
		this.mnuMain_UserInfo_MusicPath.ShortLabel = global::Mono.Unix.Catalog.GetString ("Select Music Path");
		w1.Add (this.mnuMain_UserInfo_MusicPath, null);
		this.PathActionsAction = new global::Gtk.Action ("PathActionsAction", global::Mono.Unix.Catalog.GetString ("Path Actions"), null, null);
		this.PathActionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Path Actions");
		w1.Add (this.PathActionsAction, null);
		this.CreateVariousArtistFolderAction = new global::Gtk.Action ("CreateVariousArtistFolderAction", global::Mono.Unix.Catalog.GetString ("Create Various Artist Folder"), null, null);
		this.CreateVariousArtistFolderAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create Various Artist Folder");
		w1.Add (this.CreateVariousArtistFolderAction, null);
		this.TagActionsAction = new global::Gtk.Action ("TagActionsAction", global::Mono.Unix.Catalog.GetString ("Tag Actions"), null, null);
		this.TagActionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tag Actions");
		w1.Add (this.TagActionsAction, null);
		this.CheckAllSongTagsAction = new global::Gtk.Action ("CheckAllSongTagsAction", global::Mono.Unix.Catalog.GetString ("Check All Song Tags"), null, null);
		this.CheckAllSongTagsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Check All Song Tags");
		w1.Add (this.CheckAllSongTagsAction, null);
		this.QuitApplicationAction = new global::Gtk.Action ("QuitApplicationAction", global::Mono.Unix.Catalog.GetString ("Quit Application"), null, null);
		this.QuitApplicationAction.HideIfEmpty = false;
		this.QuitApplicationAction.IsImportant = true;
		this.QuitApplicationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit Application");
		w1.Add (this.QuitApplicationAction, null);
		this.mnuReplaceSpaceUnderscore = new global::Gtk.Action ("mnuReplaceSpaceUnderscore", global::Mono.Unix.Catalog.GetString ("Replace Space with Underscore"), null, null);
		this.mnuReplaceSpaceUnderscore.ShortLabel = global::Mono.Unix.Catalog.GetString ("Replace Space with Underscore");
		w1.Add (this.mnuReplaceSpaceUnderscore, null);
		this.mnuReplaceUnderscore = new global::Gtk.Action ("mnuReplaceUnderscore", global::Mono.Unix.Catalog.GetString ("Replace Underscore with Space"), null, null);
		this.mnuReplaceUnderscore.ShortLabel = global::Mono.Unix.Catalog.GetString ("Replace Underscore with Space");
		w1.Add (this.mnuReplaceUnderscore, null);
		this.mnuCreateArtistFolder = new global::Gtk.Action ("mnuCreateArtistFolder", global::Mono.Unix.Catalog.GetString ("Create Various Artist Folder"), null, null);
		this.mnuCreateArtistFolder.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create Various Artist Folder");
		w1.Add (this.mnuCreateArtistFolder, null);
		this.mnuShowSngTagWin = new global::Gtk.Action ("mnuShowSngTagWin", global::Mono.Unix.Catalog.GetString ("Display Song Tag Window"), null, null);
		this.mnuShowSngTagWin.ShortLabel = global::Mono.Unix.Catalog.GetString ("Display Song Tag Window");
		w1.Add (this.mnuShowSngTagWin, null);
		this.mnuQuit = new global::Gtk.Action ("mnuQuit", global::Mono.Unix.Catalog.GetString ("Quit Application"), null, null);
		this.mnuQuit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit Application");
		w1.Add (this.mnuQuit, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.mnuQuitApp = new global::Gtk.Action ("mnuQuitApp", global::Mono.Unix.Catalog.GetString ("Quit Application"), null, null);
		this.mnuQuitApp.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit Application");
		w1.Add (this.mnuQuitApp, null);
		this.mnuLoadSongs = new global::Gtk.Action ("mnuLoadSongs", global::Mono.Unix.Catalog.GetString ("Load mp3 Songs"), null, null);
		this.mnuLoadSongs.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load mp3 Songs");
		w1.Add (this.mnuLoadSongs, null);
		this.mnuMusicPath = new global::Gtk.Action ("mnuMusicPath", global::Mono.Unix.Catalog.GetString ("Select Music Path"), null, null);
		this.mnuMusicPath.ShortLabel = global::Mono.Unix.Catalog.GetString ("Select Music Path");
		w1.Add (this.mnuMusicPath, null);
		this.MusicDirectoryStructureAction = new global::Gtk.Action ("MusicDirectoryStructureAction", global::Mono.Unix.Catalog.GetString ("Music Directory Structure"), null, null);
		this.MusicDirectoryStructureAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Music Directory Structure");
		w1.Add (this.MusicDirectoryStructureAction, null);
		this.mnuMusicPath1 = new global::Gtk.Action ("mnuMusicPath1", global::Mono.Unix.Catalog.GetString ("Select Path To Music Folder"), null, null);
		this.mnuMusicPath1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Select Path To Music Folder");
		w1.Add (this.mnuMusicPath1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.WidthRequest = 800;
		this.HeightRequest = 800;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='mnuMain'><menu name='FileAction' action='FileAction'><menuitem name='mnuLoadSongs' action='mnuLoadSongs'/><separator/><menuitem name='mnuQuitApp' action='mnuQuitApp'/></menu><menu name='PathActionsAction' action='PathActionsAction'><menuitem name='mnuReplaceSpaceUnderscore' action='mnuReplaceSpaceUnderscore'/><menuitem name='mnuReplaceUnderscore' action='mnuReplaceUnderscore'/><separator/><menuitem name='mnuCreateArtistFolder' action='mnuCreateArtistFolder'/></menu><menu name='TagActionsAction' action='TagActionsAction'><menuitem name='mnuShowSngTagWin' action='mnuShowSngTagWin'/></menu><menu name='MusicDirectoryStructureAction' action='MusicDirectoryStructureAction'><menuitem name='mnuMusicPath1' action='mnuMusicPath1'/></menu></menubar></ui>");
		this.mnuMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/mnuMain")));
		this.mnuMain.Name = "mnuMain";
		this.vbox1.Add (this.mnuMain);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.mnuMain]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.aliMenuLabelInfo = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliMenuLabelInfo.HeightRequest = 30;
		this.aliMenuLabelInfo.Name = "aliMenuLabelInfo";
		this.vbox1.Add (this.aliMenuLabelInfo);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.aliMenuLabelInfo]));
		w3.Position = 1;
		w3.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.lblInfo = new global::Gtk.Label ();
		this.lblInfo.HeightRequest = 34;
		this.lblInfo.Name = "lblInfo";
		this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.lblInfo.Justify = ((global::Gtk.Justification)(2));
		this.lblInfo.SingleLineMode = true;
		this.vbox1.Add (this.lblInfo);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblInfo]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.aliLblInfo_TableUserInfo = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliLblInfo_TableUserInfo.HeightRequest = 34;
		this.aliLblInfo_TableUserInfo.Name = "aliLblInfo_TableUserInfo";
		this.vbox1.Add (this.aliLblInfo_TableUserInfo);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.aliLblInfo_TableUserInfo]));
		w5.Position = 3;
		w5.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.aliLeft_TableUser = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliLeft_TableUser.Name = "aliLeft_TableUser";
		this.hbox1.Add (this.aliLeft_TableUser);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.aliLeft_TableUser]));
		w6.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.tblUserInfo = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
		this.tblUserInfo.WidthRequest = 600;
		this.tblUserInfo.HeightRequest = 130;
		this.tblUserInfo.Name = "tblUserInfo";
		this.tblUserInfo.RowSpacing = ((uint)(6));
		this.tblUserInfo.ColumnSpacing = ((uint)(6));
		// Container child tblUserInfo.Gtk.Table+TableChild
		this.aliLeft_UserHome = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliLeft_UserHome.HeightRequest = 25;
		this.aliLeft_UserHome.Name = "aliLeft_UserHome";
		this.tblUserInfo.Add (this.aliLeft_UserHome);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblUserInfo [this.aliLeft_UserHome]));
		w7.TopAttach = ((uint)(3));
		w7.BottomAttach = ((uint)(4));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblUserInfo.Gtk.Table+TableChild
		this.aliLeft_UserName = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliLeft_UserName.HeightRequest = 25;
		this.aliLeft_UserName.Name = "aliLeft_UserName";
		this.tblUserInfo.Add (this.aliLeft_UserName);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tblUserInfo [this.aliLeft_UserName]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child tblUserInfo.Gtk.Table+TableChild
		this.aliRight_LblUserName = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliRight_LblUserName.Name = "aliRight_LblUserName";
		this.tblUserInfo.Add (this.aliRight_LblUserName);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblUserInfo [this.aliRight_LblUserName]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblUserInfo.Gtk.Table+TableChild
		this.aliRight_UserHomePath = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliRight_UserHomePath.Name = "aliRight_UserHomePath";
		this.tblUserInfo.Add (this.aliRight_UserHomePath);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblUserInfo [this.aliRight_UserHomePath]));
		w10.TopAttach = ((uint)(3));
		w10.BottomAttach = ((uint)(4));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblUserInfo.Gtk.Table+TableChild
		this.lblUser = new global::Gtk.Label ();
		this.lblUser.Name = "lblUser";
		this.lblUser.LabelProp = global::Mono.Unix.Catalog.GetString ("User Name:");
		this.lblUser.Justify = ((global::Gtk.Justification)(2));
		this.lblUser.SingleLineMode = true;
		this.tblUserInfo.Add (this.lblUser);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblUserInfo [this.lblUser]));
		w11.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child tblUserInfo.Gtk.Table+TableChild
		this.lblUserHome = new global::Gtk.Label ();
		this.lblUserHome.Name = "lblUserHome";
		this.lblUserHome.LabelProp = global::Mono.Unix.Catalog.GetString ("User Home");
		this.lblUserHome.Justify = ((global::Gtk.Justification)(2));
		this.lblUserHome.SingleLineMode = true;
		this.tblUserInfo.Add (this.lblUserHome);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblUserInfo [this.lblUserHome]));
		w12.TopAttach = ((uint)(2));
		w12.BottomAttach = ((uint)(3));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblUserInfo.Gtk.Table+TableChild
		this.lblUserHomePath = new global::Gtk.Label ();
		this.lblUserHomePath.Name = "lblUserHomePath";
		this.lblUserHomePath.LabelProp = global::Mono.Unix.Catalog.GetString ("lblUserHomePath");
		this.lblUserHomePath.Justify = ((global::Gtk.Justification)(2));
		this.lblUserHomePath.SingleLineMode = true;
		this.tblUserInfo.Add (this.lblUserHomePath);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblUserInfo [this.lblUserHomePath]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblUserInfo.Gtk.Table+TableChild
		this.lblUserMusic = new global::Gtk.Label ();
		this.lblUserMusic.Name = "lblUserMusic";
		this.lblUserMusic.LabelProp = global::Mono.Unix.Catalog.GetString ("User Music ");
		this.lblUserMusic.Justify = ((global::Gtk.Justification)(2));
		this.lblUserMusic.SingleLineMode = true;
		this.tblUserInfo.Add (this.lblUserMusic);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tblUserInfo [this.lblUserMusic]));
		w14.TopAttach = ((uint)(4));
		w14.BottomAttach = ((uint)(5));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblUserInfo.Gtk.Table+TableChild
		this.lblUserMusicPath = new global::Gtk.Label ();
		this.lblUserMusicPath.Name = "lblUserMusicPath";
		this.lblUserMusicPath.LabelProp = global::Mono.Unix.Catalog.GetString ("lblUserMusicPath");
		this.lblUserMusicPath.Justify = ((global::Gtk.Justification)(2));
		this.lblUserMusicPath.SingleLineMode = true;
		this.tblUserInfo.Add (this.lblUserMusicPath);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblUserInfo [this.lblUserMusicPath]));
		w15.TopAttach = ((uint)(4));
		w15.BottomAttach = ((uint)(5));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblUserInfo.Gtk.Table+TableChild
		this.lblUserName = new global::Gtk.Label ();
		this.lblUserName.Name = "lblUserName";
		this.lblUserName.LabelProp = global::Mono.Unix.Catalog.GetString ("lblUserName");
		this.lblUserName.Justify = ((global::Gtk.Justification)(2));
		this.lblUserName.SingleLineMode = true;
		this.tblUserInfo.Add (this.lblUserName);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tblUserInfo [this.lblUserName]));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.YOptions = ((global::Gtk.AttachOptions)(0));
		this.hbox1.Add (this.tblUserInfo);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tblUserInfo]));
		w17.Position = 1;
		w17.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.aliRigth_TableUserInfo = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliRigth_TableUserInfo.Name = "aliRigth_TableUserInfo";
		this.hbox1.Add (this.aliRigth_TableUserInfo);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.aliRigth_TableUserInfo]));
		w18.Position = 2;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.aliBottom_TableUser = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliBottom_TableUser.HeightRequest = 34;
		this.aliBottom_TableUser.Name = "aliBottom_TableUser";
		this.vbox1.Add (this.aliBottom_TableUser);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.aliBottom_TableUser]));
		w20.Position = 5;
		w20.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.aliAbove_ButtonBox = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.aliAbove_ButtonBox.Name = "aliAbove_ButtonBox";
		this.vbox1.Add (this.aliAbove_ButtonBox);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.aliAbove_ButtonBox]));
		w21.Position = 8;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btnBox_Bottom = new global::Gtk.HButtonBox ();
		this.btnBox_Bottom.HeightRequest = 40;
		this.btnBox_Bottom.Name = "btnBox_Bottom";
		this.btnBox_Bottom.BorderWidth = ((uint)(4));
		// Container child btnBox_Bottom.Gtk.ButtonBox+ButtonBoxChild
		this.btnQuit = new global::Gtk.Button ();
		this.btnQuit.WidthRequest = 140;
		this.btnQuit.HeightRequest = 35;
		this.btnQuit.CanFocus = true;
		this.btnQuit.Name = "btnQuit";
		this.btnQuit.UseUnderline = true;
		this.btnQuit.BorderWidth = ((uint)(2));
		// Container child btnQuit.Gtk.Container+ContainerChild
		global::Gtk.Alignment w22 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w23 = new global::Gtk.HBox ();
		w23.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w24 = new global::Gtk.Image ();
		w24.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-quit", global::Gtk.IconSize.Menu);
		w23.Add (w24);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w26 = new global::Gtk.Label ();
		w26.LabelProp = global::Mono.Unix.Catalog.GetString ("Quit Application");
		w26.UseUnderline = true;
		w23.Add (w26);
		w22.Add (w23);
		this.btnQuit.Add (w22);
		this.btnBox_Bottom.Add (this.btnQuit);
		global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.btnBox_Bottom [this.btnQuit]));
		w30.Expand = false;
		w30.Fill = false;
		this.vbox1.Add (this.btnBox_Bottom);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnBox_Bottom]));
		w31.Position = 9;
		w31.Expand = false;
		w31.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 802;
		this.DefaultHeight = 830;
		this.Show ();
		this.mnuReplaceSpaceUnderscore.Activated += new global::System.EventHandler (this.ReplaceSpaceInFileWithUnderscoreMenu);
		this.mnuReplaceUnderscore.Activated += new global::System.EventHandler (this.ReplaceUndersoreInFileWithSpaceMenu);
		this.mnuCreateArtistFolder.Activated += new global::System.EventHandler (this.CreateVariousArtistFolderMenu);
		this.mnuShowSngTagWin.Activated += new global::System.EventHandler (this.DisplaySongTagWindowMenu);
		this.mnuQuitApp.Activated += new global::System.EventHandler (this.QuitMusicManagerProgramMenu);
		this.mnuLoadSongs.Activated += new global::System.EventHandler (this.LoadMp3SongsFromMusicFolderMenu);
		this.mnuMusicPath1.Activated += new global::System.EventHandler (this.SelectPathToMusicFolderMenu);
		this.btnQuit.Clicked += new global::System.EventHandler (this.QuitApplicationButton);
	}
}
