
// This file has been generated by the GUI designer. Do not modify.
namespace MusicManager
{
	public partial class MusicPathWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Label lblInfo;
		private global::Gtk.Table tblPathChanges;
		private global::Gtk.Label lblInsert;
		private global::Gtk.Label lblRemove;
		private global::Gtk.Label lblRemUnderscore;
		private global::Gtk.Label lblUnderscore;
		private global::Gtk.HButtonBox hbtnSetPathStructureBox;
		private global::Gtk.Button btnInsert;
		private global::Gtk.Button btnRemove;
		private global::Gtk.HButtonBox hbtnQuitBox;
		private global::Gtk.Button btnQuit;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MusicManager.MusicPathWindow
			this.WidthRequest = 1020;
			this.HeightRequest = 311;
			this.Name = "MusicManager.MusicPathWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Change Music Path Structure");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(6));
			// Container child MusicManager.MusicPathWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.HeightRequest = 19;
			this.alignment1.Name = "alignment1";
			this.vbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblInfo = new global::Gtk.Label ();
			this.lblInfo.HeightRequest = 24;
			this.lblInfo.Name = "lblInfo";
			this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.vbox1.Add (this.lblInfo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblInfo]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.tblPathChanges = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.tblPathChanges.Name = "tblPathChanges";
			this.tblPathChanges.RowSpacing = ((uint)(10));
			this.tblPathChanges.ColumnSpacing = ((uint)(10));
			this.tblPathChanges.BorderWidth = ((uint)(3));
			// Container child tblPathChanges.Gtk.Table+TableChild
			this.lblInsert = new global::Gtk.Label ();
			this.lblInsert.WidthRequest = 525;
			this.lblInsert.HeightRequest = 24;
			this.lblInsert.Name = "lblInsert";
			this.lblInsert.LabelProp = global::Mono.Unix.Catalog.GetString ("If you choose to insert underscore into the path name. The result will be:");
			this.tblPathChanges.Add (this.lblInsert);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblPathChanges [this.lblInsert]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPathChanges.Gtk.Table+TableChild
			this.lblRemove = new global::Gtk.Label ();
			this.lblRemove.HeightRequest = 24;
			this.lblRemove.Name = "lblRemove";
			this.lblRemove.LabelProp = global::Mono.Unix.Catalog.GetString ("If you choose to remove Underscore from the path name. The result will be:");
			this.tblPathChanges.Add (this.lblRemove);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblPathChanges [this.lblRemove]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPathChanges.Gtk.Table+TableChild
			this.lblRemUnderscore = new global::Gtk.Label ();
			this.lblRemUnderscore.HeightRequest = 24;
			this.lblRemUnderscore.Name = "lblRemUnderscore";
			this.lblRemUnderscore.LabelProp = global::Mono.Unix.Catalog.GetString ("Music/Artist Name/ Album Name/Song Name");
			this.tblPathChanges.Add (this.lblRemUnderscore);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblPathChanges [this.lblRemUnderscore]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPathChanges.Gtk.Table+TableChild
			this.lblUnderscore = new global::Gtk.Label ();
			this.lblUnderscore.WidthRequest = 465;
			this.lblUnderscore.HeightRequest = 24;
			this.lblUnderscore.Name = "lblUnderscore";
			this.lblUnderscore.LabelProp = global::Mono.Unix.Catalog.GetString ("Music/Artist_Name/Album_Name/Song_Name");
			this.tblPathChanges.Add (this.lblUnderscore);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblPathChanges [this.lblUnderscore]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.tblPathChanges);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.tblPathChanges]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbtnSetPathStructureBox = new global::Gtk.HButtonBox ();
			this.hbtnSetPathStructureBox.HeightRequest = 50;
			this.hbtnSetPathStructureBox.Name = "hbtnSetPathStructureBox";
			this.hbtnSetPathStructureBox.BorderWidth = ((uint)(4));
			this.hbtnSetPathStructureBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbtnSetPathStructureBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnInsert = new global::Gtk.Button ();
			this.btnInsert.CanFocus = true;
			this.btnInsert.Name = "btnInsert";
			this.btnInsert.UseUnderline = true;
			this.btnInsert.BorderWidth = ((uint)(2));
			// Container child btnInsert.Gtk.Container+ContainerChild
			global::Gtk.Alignment w8 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w9 = new global::Gtk.HBox ();
			w9.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w10 = new global::Gtk.Image ();
			w10.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w9.Add (w10);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w12 = new global::Gtk.Label ();
			w12.LabelProp = global::Mono.Unix.Catalog.GetString ("Insert-Underscore");
			w12.UseUnderline = true;
			w9.Add (w12);
			w8.Add (w9);
			this.btnInsert.Add (w8);
			this.hbtnSetPathStructureBox.Add (this.btnInsert);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnSetPathStructureBox [this.btnInsert]));
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbtnSetPathStructureBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnRemove = new global::Gtk.Button ();
			this.btnRemove.CanFocus = true;
			this.btnRemove.Name = "btnRemove";
			this.btnRemove.UseUnderline = true;
			this.btnRemove.BorderWidth = ((uint)(2));
			// Container child btnRemove.Gtk.Container+ContainerChild
			global::Gtk.Alignment w17 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w18 = new global::Gtk.HBox ();
			w18.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w19 = new global::Gtk.Image ();
			w19.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w18.Add (w19);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w21 = new global::Gtk.Label ();
			w21.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove-Underscore");
			w21.UseUnderline = true;
			w18.Add (w21);
			w17.Add (w18);
			this.btnRemove.Add (w17);
			this.hbtnSetPathStructureBox.Add (this.btnRemove);
			global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnSetPathStructureBox [this.btnRemove]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox1.Add (this.hbtnSetPathStructureBox);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbtnSetPathStructureBox]));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbtnQuitBox = new global::Gtk.HButtonBox ();
			this.hbtnQuitBox.HeightRequest = 52;
			this.hbtnQuitBox.Name = "hbtnQuitBox";
			this.hbtnQuitBox.BorderWidth = ((uint)(12));
			this.hbtnQuitBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbtnQuitBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnQuit = new global::Gtk.Button ();
			this.btnQuit.WidthRequest = 100;
			this.btnQuit.HeightRequest = 30;
			this.btnQuit.CanFocus = true;
			this.btnQuit.Name = "btnQuit";
			this.btnQuit.UseUnderline = true;
			this.btnQuit.BorderWidth = ((uint)(2));
			// Container child btnQuit.Gtk.Container+ContainerChild
			global::Gtk.Alignment w27 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w28 = new global::Gtk.HBox ();
			w28.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w29 = new global::Gtk.Image ();
			w29.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-quit", global::Gtk.IconSize.Menu);
			w28.Add (w29);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w31 = new global::Gtk.Label ();
			w31.LabelProp = global::Mono.Unix.Catalog.GetString ("Quit");
			w31.UseUnderline = true;
			w28.Add (w31);
			w27.Add (w28);
			this.btnQuit.Add (w27);
			this.hbtnQuitBox.Add (this.btnQuit);
			global::Gtk.ButtonBox.ButtonBoxChild w35 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnQuitBox [this.btnQuit]));
			w35.Expand = false;
			w35.Fill = false;
			this.vbox1.Add (this.hbtnQuitBox);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbtnQuitBox]));
			w36.Position = 4;
			w36.Expand = false;
			w36.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1022;
			this.DefaultHeight = 341;
			this.Show ();
			this.btnQuit.Clicked += new global::System.EventHandler (this.QuitChangeMusicPathStructureWindowButton);
		}
	}
}
