
// This file has been generated by the GUI designer. Do not modify.
namespace MusicManager
{
	public partial class SongTagWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Alignment aliTop;
		private global::Gtk.Label lblInfo;
		private global::Gtk.Table tblTag;
		private global::Gtk.Label lblAlbum;
		private global::Gtk.Label lblAlbumArt;
		private global::Gtk.Label lblArtist;
		private global::Gtk.Label lblDiscCount;
		private global::Gtk.Label lblDiscNum;
		private global::Gtk.Label lblGenre;
		private global::Gtk.Label lblSong;
		private global::Gtk.Label lblTrackCount;
		private global::Gtk.Label lblTrackNum;
		private global::Gtk.Label lblYear;
		private global::Gtk.Entry txtAlbum;
		private global::Gtk.Entry txtAlbumArt;
		private global::Gtk.Entry txtArtist;
		private global::Gtk.Entry txtDiscCount;
		private global::Gtk.Entry txtDiscNum;
		private global::Gtk.Entry txtGenre;
		private global::Gtk.Entry txtSong;
		private global::Gtk.Entry txtTrackCount;
		private global::Gtk.Entry txtTrackNum;
		private global::Gtk.Entry txtYear;
		private global::Gtk.HBox hbox5;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button btnEditTag;
		private global::Gtk.Button btnEditCancel;
		private global::Gtk.Button btnEditUpdate;
		private global::Gtk.Button btnEditOpen;
		private global::Gtk.Alignment aliBetweenbtnDatabtnMove;
		private global::Gtk.HButtonBox hbtnMoveBox;
		private global::Gtk.Button btnFirst;
		private global::Gtk.Button btnPrevious;
		private global::Gtk.Button btnNext;
		private global::Gtk.Button btnLast;
		private global::Gtk.HButtonBox hbuttonbox3;
		private global::Gtk.Button btnLoadTags;
		private global::Gtk.Button btnErrorTags;
		private global::Gtk.Button btnValidTags;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label lblArtistPath;
		private global::Gtk.Alignment aliBetweenlblArtistPathtxtPath;
		private global::Gtk.Entry txtArtistPath;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label lblAlbumPath;
		private global::Gtk.Alignment aliBetweenlblAlbumtxtAlbum;
		private global::Gtk.Entry txtAlbumPath;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label lblSongPath;
		private global::Gtk.Alignment aliBetweenlblSongPathtxtSongPath;
		private global::Gtk.Entry txtSongPath;
		private global::Gtk.HButtonBox hbtnWindowBox;
		private global::Gtk.Button btnQuit;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MusicManager.SongTagWindow
			this.WidthRequest = 1020;
			this.HeightRequest = 525;
			this.Name = "MusicManager.SongTagWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SongTagWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(6));
			// Container child MusicManager.SongTagWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 10;
			// Container child vbox2.Gtk.Box+BoxChild
			this.aliTop = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.aliTop.HeightRequest = 19;
			this.aliTop.Name = "aliTop";
			this.vbox2.Add (this.aliTop);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.aliTop]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblInfo = new global::Gtk.Label ();
			this.lblInfo.HeightRequest = 24;
			this.lblInfo.Name = "lblInfo";
			this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("lblInfo");
			this.lblInfo.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add (this.lblInfo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblInfo]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.tblTag = new global::Gtk.Table (((uint)(5)), ((uint)(4)), false);
			this.tblTag.Name = "tblTag";
			this.tblTag.RowSpacing = ((uint)(10));
			this.tblTag.ColumnSpacing = ((uint)(10));
			this.tblTag.BorderWidth = ((uint)(3));
			// Container child tblTag.Gtk.Table+TableChild
			this.lblAlbum = new global::Gtk.Label ();
			this.lblAlbum.WidthRequest = 175;
			this.lblAlbum.HeightRequest = 24;
			this.lblAlbum.Name = "lblAlbum";
			this.lblAlbum.LabelProp = global::Mono.Unix.Catalog.GetString ("Album Name:");
			this.lblAlbum.Justify = ((global::Gtk.Justification)(2));
			this.tblTag.Add (this.lblAlbum);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblAlbum]));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.lblAlbumArt = new global::Gtk.Label ();
			this.lblAlbumArt.WidthRequest = 175;
			this.lblAlbumArt.HeightRequest = 24;
			this.lblAlbumArt.Name = "lblAlbumArt";
			this.lblAlbumArt.LabelProp = global::Mono.Unix.Catalog.GetString ("Album Art Count:");
			this.lblAlbumArt.Justify = ((global::Gtk.Justification)(2));
			this.tblTag.Add (this.lblAlbumArt);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblAlbumArt]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.lblArtist = new global::Gtk.Label ();
			this.lblArtist.WidthRequest = 175;
			this.lblArtist.HeightRequest = 24;
			this.lblArtist.Name = "lblArtist";
			this.lblArtist.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist Name:");
			this.lblArtist.Justify = ((global::Gtk.Justification)(2));
			this.tblTag.Add (this.lblArtist);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblArtist]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.lblDiscCount = new global::Gtk.Label ();
			this.lblDiscCount.WidthRequest = 175;
			this.lblDiscCount.HeightRequest = 24;
			this.lblDiscCount.Name = "lblDiscCount";
			this.lblDiscCount.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Discs:");
			this.lblDiscCount.Justify = ((global::Gtk.Justification)(2));
			this.tblTag.Add (this.lblDiscCount);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblDiscCount]));
			w6.TopAttach = ((uint)(4));
			w6.BottomAttach = ((uint)(5));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.lblDiscNum = new global::Gtk.Label ();
			this.lblDiscNum.WidthRequest = 175;
			this.lblDiscNum.HeightRequest = 24;
			this.lblDiscNum.Name = "lblDiscNum";
			this.lblDiscNum.LabelProp = global::Mono.Unix.Catalog.GetString ("Disc Number:");
			this.lblDiscNum.Justify = ((global::Gtk.Justification)(2));
			this.tblTag.Add (this.lblDiscNum);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblDiscNum]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.lblGenre = new global::Gtk.Label ();
			this.lblGenre.WidthRequest = 175;
			this.lblGenre.HeightRequest = 24;
			this.lblGenre.Name = "lblGenre";
			this.lblGenre.LabelProp = global::Mono.Unix.Catalog.GetString ("Genre:");
			this.lblGenre.Justify = ((global::Gtk.Justification)(2));
			this.tblTag.Add (this.lblGenre);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblGenre]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(2));
			w8.RightAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.lblSong = new global::Gtk.Label ();
			this.lblSong.WidthRequest = 175;
			this.lblSong.HeightRequest = 24;
			this.lblSong.Name = "lblSong";
			this.lblSong.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Name:");
			this.lblSong.Justify = ((global::Gtk.Justification)(2));
			this.tblTag.Add (this.lblSong);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblSong]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.lblTrackCount = new global::Gtk.Label ();
			this.lblTrackCount.WidthRequest = 175;
			this.lblTrackCount.HeightRequest = 24;
			this.lblTrackCount.Name = "lblTrackCount";
			this.lblTrackCount.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Tracks:");
			this.lblTrackCount.Justify = ((global::Gtk.Justification)(2));
			this.tblTag.Add (this.lblTrackCount);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblTrackCount]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.lblTrackNum = new global::Gtk.Label ();
			this.lblTrackNum.WidthRequest = 175;
			this.lblTrackNum.HeightRequest = 24;
			this.lblTrackNum.Name = "lblTrackNum";
			this.lblTrackNum.LabelProp = global::Mono.Unix.Catalog.GetString ("Track Number:");
			this.lblTrackNum.Justify = ((global::Gtk.Justification)(2));
			this.tblTag.Add (this.lblTrackNum);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblTrackNum]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.lblYear = new global::Gtk.Label ();
			this.lblYear.WidthRequest = 175;
			this.lblYear.HeightRequest = 24;
			this.lblYear.Name = "lblYear";
			this.lblYear.LabelProp = global::Mono.Unix.Catalog.GetString ("Year:");
			this.tblTag.Add (this.lblYear);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblTag [this.lblYear]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.txtAlbum = new global::Gtk.Entry ();
			this.txtAlbum.WidthRequest = 240;
			this.txtAlbum.CanFocus = true;
			this.txtAlbum.Name = "txtAlbum";
			this.txtAlbum.Text = global::Mono.Unix.Catalog.GetString ("txtAlbum");
			this.txtAlbum.IsEditable = false;
			this.txtAlbum.InvisibleChar = '•';
			this.tblTag.Add (this.txtAlbum);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtAlbum]));
			w13.LeftAttach = ((uint)(3));
			w13.RightAttach = ((uint)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.txtAlbumArt = new global::Gtk.Entry ();
			this.txtAlbumArt.WidthRequest = 240;
			this.txtAlbumArt.HeightRequest = 24;
			this.txtAlbumArt.CanFocus = true;
			this.txtAlbumArt.Name = "txtAlbumArt";
			this.txtAlbumArt.Text = global::Mono.Unix.Catalog.GetString ("txtAlbumArt");
			this.txtAlbumArt.IsEditable = false;
			this.txtAlbumArt.InvisibleChar = '•';
			this.tblTag.Add (this.txtAlbumArt);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtAlbumArt]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.txtArtist = new global::Gtk.Entry ();
			this.txtArtist.WidthRequest = 240;
			this.txtArtist.HeightRequest = 24;
			this.txtArtist.CanFocus = true;
			this.txtArtist.Name = "txtArtist";
			this.txtArtist.Text = global::Mono.Unix.Catalog.GetString ("txtArtist");
			this.txtArtist.IsEditable = false;
			this.txtArtist.InvisibleChar = '•';
			this.tblTag.Add (this.txtArtist);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtArtist]));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.txtDiscCount = new global::Gtk.Entry ();
			this.txtDiscCount.WidthRequest = 240;
			this.txtDiscCount.HeightRequest = 24;
			this.txtDiscCount.CanFocus = true;
			this.txtDiscCount.Name = "txtDiscCount";
			this.txtDiscCount.Text = global::Mono.Unix.Catalog.GetString ("txtDiscCount");
			this.txtDiscCount.IsEditable = false;
			this.txtDiscCount.InvisibleChar = '•';
			this.tblTag.Add (this.txtDiscCount);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtDiscCount]));
			w16.TopAttach = ((uint)(4));
			w16.BottomAttach = ((uint)(5));
			w16.LeftAttach = ((uint)(3));
			w16.RightAttach = ((uint)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.txtDiscNum = new global::Gtk.Entry ();
			this.txtDiscNum.WidthRequest = 240;
			this.txtDiscNum.HeightRequest = 24;
			this.txtDiscNum.CanFocus = true;
			this.txtDiscNum.Name = "txtDiscNum";
			this.txtDiscNum.Text = global::Mono.Unix.Catalog.GetString ("txtDiscNum");
			this.txtDiscNum.IsEditable = false;
			this.txtDiscNum.InvisibleChar = '•';
			this.tblTag.Add (this.txtDiscNum);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtDiscNum]));
			w17.TopAttach = ((uint)(4));
			w17.BottomAttach = ((uint)(5));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.txtGenre = new global::Gtk.Entry ();
			this.txtGenre.WidthRequest = 240;
			this.txtGenre.HeightRequest = 24;
			this.txtGenre.CanFocus = true;
			this.txtGenre.Name = "txtGenre";
			this.txtGenre.Text = global::Mono.Unix.Catalog.GetString ("txtGenre");
			this.txtGenre.IsEditable = false;
			this.txtGenre.InvisibleChar = '•';
			this.tblTag.Add (this.txtGenre);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtGenre]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(3));
			w18.RightAttach = ((uint)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.txtSong = new global::Gtk.Entry ();
			this.txtSong.WidthRequest = 240;
			this.txtSong.HeightRequest = 24;
			this.txtSong.CanFocus = true;
			this.txtSong.Name = "txtSong";
			this.txtSong.Text = global::Mono.Unix.Catalog.GetString ("tstSong");
			this.txtSong.IsEditable = false;
			this.txtSong.InvisibleChar = '•';
			this.tblTag.Add (this.txtSong);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtSong]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.txtTrackCount = new global::Gtk.Entry ();
			this.txtTrackCount.WidthRequest = 240;
			this.txtTrackCount.HeightRequest = 24;
			this.txtTrackCount.CanFocus = true;
			this.txtTrackCount.Name = "txtTrackCount";
			this.txtTrackCount.Text = global::Mono.Unix.Catalog.GetString ("txtTrackCount");
			this.txtTrackCount.IsEditable = false;
			this.txtTrackCount.InvisibleChar = '•';
			this.tblTag.Add (this.txtTrackCount);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtTrackCount]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.LeftAttach = ((uint)(3));
			w20.RightAttach = ((uint)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.txtTrackNum = new global::Gtk.Entry ();
			this.txtTrackNum.WidthRequest = 240;
			this.txtTrackNum.HeightRequest = 24;
			this.txtTrackNum.CanFocus = true;
			this.txtTrackNum.Name = "txtTrackNum";
			this.txtTrackNum.Text = global::Mono.Unix.Catalog.GetString ("txtTrackNum");
			this.txtTrackNum.IsEditable = false;
			this.txtTrackNum.InvisibleChar = '•';
			this.tblTag.Add (this.txtTrackNum);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtTrackNum]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTag.Gtk.Table+TableChild
			this.txtYear = new global::Gtk.Entry ();
			this.txtYear.WidthRequest = 240;
			this.txtYear.HeightRequest = 24;
			this.txtYear.CanFocus = true;
			this.txtYear.Name = "txtYear";
			this.txtYear.Text = global::Mono.Unix.Catalog.GetString ("txtYear");
			this.txtYear.IsEditable = false;
			this.txtYear.InvisibleChar = '•';
			this.tblTag.Add (this.txtYear);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tblTag [this.txtYear]));
			w22.TopAttach = ((uint)(3));
			w22.BottomAttach = ((uint)(4));
			w22.LeftAttach = ((uint)(3));
			w22.RightAttach = ((uint)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.tblTag);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tblTag]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.HeightRequest = 45;
			this.hbuttonbox1.Name = "hbuttonbox1";
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnEditTag = new global::Gtk.Button ();
			this.btnEditTag.Sensitive = false;
			this.btnEditTag.CanFocus = true;
			this.btnEditTag.Name = "btnEditTag";
			this.btnEditTag.UseUnderline = true;
			// Container child btnEditTag.Gtk.Container+ContainerChild
			global::Gtk.Alignment w24 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w25 = new global::Gtk.HBox ();
			w25.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w26 = new global::Gtk.Image ();
			w26.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w25.Add (w26);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w28 = new global::Gtk.Label ();
			w28.LabelProp = global::Mono.Unix.Catalog.GetString ("Edit Tag");
			w28.UseUnderline = true;
			w25.Add (w28);
			w24.Add (w25);
			this.btnEditTag.Add (w24);
			this.hbuttonbox1.Add (this.btnEditTag);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnEditTag]));
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnEditCancel = new global::Gtk.Button ();
			this.btnEditCancel.Sensitive = false;
			this.btnEditCancel.CanFocus = true;
			this.btnEditCancel.Name = "btnEditCancel";
			this.btnEditCancel.UseUnderline = true;
			this.btnEditCancel.BorderWidth = ((uint)(2));
			// Container child btnEditCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w33 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w34 = new global::Gtk.HBox ();
			w34.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w35 = new global::Gtk.Image ();
			w35.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w34.Add (w35);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w37 = new global::Gtk.Label ();
			w37.LabelProp = global::Mono.Unix.Catalog.GetString ("Cancel");
			w37.UseUnderline = true;
			w34.Add (w37);
			w33.Add (w34);
			this.btnEditCancel.Add (w33);
			this.hbuttonbox1.Add (this.btnEditCancel);
			global::Gtk.ButtonBox.ButtonBoxChild w41 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnEditCancel]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnEditUpdate = new global::Gtk.Button ();
			this.btnEditUpdate.Sensitive = false;
			this.btnEditUpdate.CanFocus = true;
			this.btnEditUpdate.Name = "btnEditUpdate";
			this.btnEditUpdate.UseUnderline = true;
			this.btnEditUpdate.BorderWidth = ((uint)(2));
			// Container child btnEditUpdate.Gtk.Container+ContainerChild
			global::Gtk.Alignment w42 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w43 = new global::Gtk.HBox ();
			w43.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w44 = new global::Gtk.Image ();
			w44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Menu);
			w43.Add (w44);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w46 = new global::Gtk.Label ();
			w46.LabelProp = global::Mono.Unix.Catalog.GetString ("Update");
			w46.UseUnderline = true;
			w43.Add (w46);
			w42.Add (w43);
			this.btnEditUpdate.Add (w42);
			this.hbuttonbox1.Add (this.btnEditUpdate);
			global::Gtk.ButtonBox.ButtonBoxChild w50 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnEditUpdate]));
			w50.Position = 2;
			w50.Expand = false;
			w50.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnEditOpen = new global::Gtk.Button ();
			this.btnEditOpen.Sensitive = false;
			this.btnEditOpen.CanFocus = true;
			this.btnEditOpen.Name = "btnEditOpen";
			this.btnEditOpen.UseUnderline = true;
			// Container child btnEditOpen.Gtk.Container+ContainerChild
			global::Gtk.Alignment w51 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w52 = new global::Gtk.HBox ();
			w52.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w53 = new global::Gtk.Image ();
			w53.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			w52.Add (w53);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w55 = new global::Gtk.Label ();
			w55.LabelProp = global::Mono.Unix.Catalog.GetString ("Open");
			w55.UseUnderline = true;
			w52.Add (w55);
			w51.Add (w52);
			this.btnEditOpen.Add (w51);
			this.hbuttonbox1.Add (this.btnEditOpen);
			global::Gtk.ButtonBox.ButtonBoxChild w59 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnEditOpen]));
			w59.Position = 3;
			w59.Expand = false;
			w59.Fill = false;
			this.hbox5.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hbuttonbox1]));
			w60.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.aliBetweenbtnDatabtnMove = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.aliBetweenbtnDatabtnMove.WidthRequest = 10;
			this.aliBetweenbtnDatabtnMove.HeightRequest = 35;
			this.aliBetweenbtnDatabtnMove.Name = "aliBetweenbtnDatabtnMove";
			this.hbox5.Add (this.aliBetweenbtnDatabtnMove);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.aliBetweenbtnDatabtnMove]));
			w61.Position = 1;
			w61.Expand = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbtnMoveBox = new global::Gtk.HButtonBox ();
			this.hbtnMoveBox.HeightRequest = 45;
			this.hbtnMoveBox.Name = "hbtnMoveBox";
			this.hbtnMoveBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbtnMoveBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnFirst = new global::Gtk.Button ();
			this.btnFirst.Sensitive = false;
			this.btnFirst.CanFocus = true;
			this.btnFirst.Name = "btnFirst";
			this.btnFirst.UseUnderline = true;
			this.btnFirst.BorderWidth = ((uint)(2));
			// Container child btnFirst.Gtk.Container+ContainerChild
			global::Gtk.Alignment w62 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w63 = new global::Gtk.HBox ();
			w63.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w64 = new global::Gtk.Image ();
			w64.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-first", global::Gtk.IconSize.Menu);
			w63.Add (w64);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w66 = new global::Gtk.Label ();
			w66.LabelProp = global::Mono.Unix.Catalog.GetString ("Move First");
			w66.UseUnderline = true;
			w63.Add (w66);
			w62.Add (w63);
			this.btnFirst.Add (w62);
			this.hbtnMoveBox.Add (this.btnFirst);
			global::Gtk.ButtonBox.ButtonBoxChild w70 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnMoveBox [this.btnFirst]));
			w70.Expand = false;
			w70.Fill = false;
			// Container child hbtnMoveBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnPrevious = new global::Gtk.Button ();
			this.btnPrevious.Sensitive = false;
			this.btnPrevious.CanFocus = true;
			this.btnPrevious.Name = "btnPrevious";
			this.btnPrevious.UseUnderline = true;
			this.btnPrevious.BorderWidth = ((uint)(2));
			// Container child btnPrevious.Gtk.Container+ContainerChild
			global::Gtk.Alignment w71 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w72 = new global::Gtk.HBox ();
			w72.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w73 = new global::Gtk.Image ();
			w73.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
			w72.Add (w73);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w75 = new global::Gtk.Label ();
			w75.LabelProp = global::Mono.Unix.Catalog.GetString ("Move Previous");
			w75.UseUnderline = true;
			w72.Add (w75);
			w71.Add (w72);
			this.btnPrevious.Add (w71);
			this.hbtnMoveBox.Add (this.btnPrevious);
			global::Gtk.ButtonBox.ButtonBoxChild w79 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnMoveBox [this.btnPrevious]));
			w79.Position = 1;
			w79.Expand = false;
			w79.Fill = false;
			// Container child hbtnMoveBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnNext = new global::Gtk.Button ();
			this.btnNext.Sensitive = false;
			this.btnNext.CanFocus = true;
			this.btnNext.Name = "btnNext";
			this.btnNext.UseUnderline = true;
			this.btnNext.BorderWidth = ((uint)(2));
			// Container child btnNext.Gtk.Container+ContainerChild
			global::Gtk.Alignment w80 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w81 = new global::Gtk.HBox ();
			w81.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w82 = new global::Gtk.Image ();
			w82.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			w81.Add (w82);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w84 = new global::Gtk.Label ();
			w84.LabelProp = global::Mono.Unix.Catalog.GetString ("Move Next");
			w84.UseUnderline = true;
			w81.Add (w84);
			w80.Add (w81);
			this.btnNext.Add (w80);
			this.hbtnMoveBox.Add (this.btnNext);
			global::Gtk.ButtonBox.ButtonBoxChild w88 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnMoveBox [this.btnNext]));
			w88.Position = 2;
			w88.Expand = false;
			w88.Fill = false;
			// Container child hbtnMoveBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnLast = new global::Gtk.Button ();
			this.btnLast.Sensitive = false;
			this.btnLast.CanFocus = true;
			this.btnLast.Name = "btnLast";
			this.btnLast.UseUnderline = true;
			this.btnLast.BorderWidth = ((uint)(2));
			// Container child btnLast.Gtk.Container+ContainerChild
			global::Gtk.Alignment w89 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w90 = new global::Gtk.HBox ();
			w90.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w91 = new global::Gtk.Image ();
			w91.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-last", global::Gtk.IconSize.Menu);
			w90.Add (w91);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w93 = new global::Gtk.Label ();
			w93.LabelProp = global::Mono.Unix.Catalog.GetString ("Move Last");
			w93.UseUnderline = true;
			w90.Add (w93);
			w89.Add (w90);
			this.btnLast.Add (w89);
			this.hbtnMoveBox.Add (this.btnLast);
			global::Gtk.ButtonBox.ButtonBoxChild w97 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnMoveBox [this.btnLast]));
			w97.Position = 3;
			w97.Expand = false;
			w97.Fill = false;
			this.hbox5.Add (this.hbtnMoveBox);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hbtnMoveBox]));
			w98.Position = 2;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w99.Position = 3;
			w99.Expand = false;
			w99.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox3 = new global::Gtk.HButtonBox ();
			this.hbuttonbox3.HeightRequest = 50;
			this.hbuttonbox3.Name = "hbuttonbox3";
			this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.btnLoadTags = new global::Gtk.Button ();
			this.btnLoadTags.CanFocus = true;
			this.btnLoadTags.Name = "btnLoadTags";
			this.btnLoadTags.UseUnderline = true;
			this.btnLoadTags.BorderWidth = ((uint)(2));
			// Container child btnLoadTags.Gtk.Container+ContainerChild
			global::Gtk.Alignment w100 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w101 = new global::Gtk.HBox ();
			w101.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w102 = new global::Gtk.Image ();
			w102.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			w101.Add (w102);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w104 = new global::Gtk.Label ();
			w104.LabelProp = global::Mono.Unix.Catalog.GetString ("Load Song Tags");
			w104.UseUnderline = true;
			w101.Add (w104);
			w100.Add (w101);
			this.btnLoadTags.Add (w100);
			this.hbuttonbox3.Add (this.btnLoadTags);
			global::Gtk.ButtonBox.ButtonBoxChild w108 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.btnLoadTags]));
			w108.Expand = false;
			w108.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.btnErrorTags = new global::Gtk.Button ();
			this.btnErrorTags.Sensitive = false;
			this.btnErrorTags.CanFocus = true;
			this.btnErrorTags.Name = "btnErrorTags";
			this.btnErrorTags.UseUnderline = true;
			this.btnErrorTags.BorderWidth = ((uint)(2));
			// Container child btnErrorTags.Gtk.Container+ContainerChild
			global::Gtk.Alignment w109 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w110 = new global::Gtk.HBox ();
			w110.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w111 = new global::Gtk.Image ();
			w111.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
			w110.Add (w111);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w113 = new global::Gtk.Label ();
			w113.LabelProp = global::Mono.Unix.Catalog.GetString ("Show Error Tags");
			w113.UseUnderline = true;
			w110.Add (w113);
			w109.Add (w110);
			this.btnErrorTags.Add (w109);
			this.hbuttonbox3.Add (this.btnErrorTags);
			global::Gtk.ButtonBox.ButtonBoxChild w117 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.btnErrorTags]));
			w117.Position = 1;
			w117.Expand = false;
			w117.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.btnValidTags = new global::Gtk.Button ();
			this.btnValidTags.Sensitive = false;
			this.btnValidTags.CanFocus = true;
			this.btnValidTags.Name = "btnValidTags";
			this.btnValidTags.UseUnderline = true;
			this.btnValidTags.BorderWidth = ((uint)(2));
			// Container child btnValidTags.Gtk.Container+ContainerChild
			global::Gtk.Alignment w118 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w119 = new global::Gtk.HBox ();
			w119.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w120 = new global::Gtk.Image ();
			w120.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Menu);
			w119.Add (w120);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w122 = new global::Gtk.Label ();
			w122.LabelProp = global::Mono.Unix.Catalog.GetString ("Show Valid Tags");
			w122.UseUnderline = true;
			w119.Add (w122);
			w118.Add (w119);
			this.btnValidTags.Add (w118);
			this.hbuttonbox3.Add (this.btnValidTags);
			global::Gtk.ButtonBox.ButtonBoxChild w126 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.btnValidTags]));
			w126.Position = 2;
			w126.Expand = false;
			w126.Fill = false;
			this.vbox2.Add (this.hbuttonbox3);
			global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox3]));
			w127.Position = 4;
			w127.Expand = false;
			w127.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblArtistPath = new global::Gtk.Label ();
			this.lblArtistPath.WidthRequest = 175;
			this.lblArtistPath.HeightRequest = 24;
			this.lblArtistPath.Name = "lblArtistPath";
			this.lblArtistPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist Folder Path:");
			this.lblArtistPath.Justify = ((global::Gtk.Justification)(2));
			this.hbox2.Add (this.lblArtistPath);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblArtistPath]));
			w128.Position = 0;
			w128.Expand = false;
			w128.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.aliBetweenlblArtistPathtxtPath = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.aliBetweenlblArtistPathtxtPath.WidthRequest = 15;
			this.aliBetweenlblArtistPathtxtPath.HeightRequest = 24;
			this.aliBetweenlblArtistPathtxtPath.Name = "aliBetweenlblArtistPathtxtPath";
			this.hbox2.Add (this.aliBetweenlblArtistPathtxtPath);
			global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.aliBetweenlblArtistPathtxtPath]));
			w129.Position = 1;
			w129.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.txtArtistPath = new global::Gtk.Entry ();
			this.txtArtistPath.WidthRequest = 801;
			this.txtArtistPath.HeightRequest = 24;
			this.txtArtistPath.CanFocus = true;
			this.txtArtistPath.Name = "txtArtistPath";
			this.txtArtistPath.Text = global::Mono.Unix.Catalog.GetString ("txtArtistPath");
			this.txtArtistPath.IsEditable = false;
			this.txtArtistPath.InvisibleChar = '•';
			this.hbox2.Add (this.txtArtistPath);
			global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtArtistPath]));
			w130.Position = 2;
			w130.Expand = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w131.Position = 5;
			w131.Expand = false;
			w131.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblAlbumPath = new global::Gtk.Label ();
			this.lblAlbumPath.WidthRequest = 175;
			this.lblAlbumPath.HeightRequest = 24;
			this.lblAlbumPath.Name = "lblAlbumPath";
			this.lblAlbumPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Album Folder Path:");
			this.lblAlbumPath.Justify = ((global::Gtk.Justification)(2));
			this.hbox3.Add (this.lblAlbumPath);
			global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblAlbumPath]));
			w132.Position = 0;
			w132.Expand = false;
			w132.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.aliBetweenlblAlbumtxtAlbum = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.aliBetweenlblAlbumtxtAlbum.WidthRequest = 15;
			this.aliBetweenlblAlbumtxtAlbum.HeightRequest = 24;
			this.aliBetweenlblAlbumtxtAlbum.Name = "aliBetweenlblAlbumtxtAlbum";
			this.hbox3.Add (this.aliBetweenlblAlbumtxtAlbum);
			global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.aliBetweenlblAlbumtxtAlbum]));
			w133.Position = 1;
			w133.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtAlbumPath = new global::Gtk.Entry ();
			this.txtAlbumPath.WidthRequest = 801;
			this.txtAlbumPath.CanFocus = true;
			this.txtAlbumPath.Name = "txtAlbumPath";
			this.txtAlbumPath.Text = global::Mono.Unix.Catalog.GetString ("txtAlbumPath");
			this.txtAlbumPath.IsEditable = false;
			this.txtAlbumPath.InvisibleChar = '•';
			this.hbox3.Add (this.txtAlbumPath);
			global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtAlbumPath]));
			w134.Position = 2;
			w134.Expand = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w135.Position = 6;
			w135.Expand = false;
			w135.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblSongPath = new global::Gtk.Label ();
			this.lblSongPath.WidthRequest = 175;
			this.lblSongPath.HeightRequest = 24;
			this.lblSongPath.Name = "lblSongPath";
			this.lblSongPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Song File Path:");
			this.lblSongPath.Justify = ((global::Gtk.Justification)(2));
			this.hbox4.Add (this.lblSongPath);
			global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblSongPath]));
			w136.Position = 0;
			w136.Expand = false;
			w136.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.aliBetweenlblSongPathtxtSongPath = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.aliBetweenlblSongPathtxtSongPath.WidthRequest = 15;
			this.aliBetweenlblSongPathtxtSongPath.HeightRequest = 24;
			this.aliBetweenlblSongPathtxtSongPath.Name = "aliBetweenlblSongPathtxtSongPath";
			this.hbox4.Add (this.aliBetweenlblSongPathtxtSongPath);
			global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.aliBetweenlblSongPathtxtSongPath]));
			w137.Position = 1;
			w137.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.txtSongPath = new global::Gtk.Entry ();
			this.txtSongPath.WidthRequest = 801;
			this.txtSongPath.HeightRequest = 24;
			this.txtSongPath.CanFocus = true;
			this.txtSongPath.Name = "txtSongPath";
			this.txtSongPath.Text = global::Mono.Unix.Catalog.GetString ("txtSongPath");
			this.txtSongPath.IsEditable = false;
			this.txtSongPath.InvisibleChar = '•';
			this.hbox4.Add (this.txtSongPath);
			global::Gtk.Box.BoxChild w138 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.txtSongPath]));
			w138.Position = 2;
			w138.Expand = false;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
			w139.Position = 7;
			w139.Expand = false;
			w139.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbtnWindowBox = new global::Gtk.HButtonBox ();
			this.hbtnWindowBox.WidthRequest = 805;
			this.hbtnWindowBox.HeightRequest = 52;
			this.hbtnWindowBox.Name = "hbtnWindowBox";
			this.hbtnWindowBox.Spacing = 50;
			this.hbtnWindowBox.BorderWidth = ((uint)(12));
			this.hbtnWindowBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbtnWindowBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnQuit = new global::Gtk.Button ();
			this.btnQuit.CanFocus = true;
			this.btnQuit.Name = "btnQuit";
			this.btnQuit.UseUnderline = true;
			// Container child btnQuit.Gtk.Container+ContainerChild
			global::Gtk.Alignment w140 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w141 = new global::Gtk.HBox ();
			w141.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w142 = new global::Gtk.Image ();
			w142.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-quit", global::Gtk.IconSize.Menu);
			w141.Add (w142);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w144 = new global::Gtk.Label ();
			w144.LabelProp = global::Mono.Unix.Catalog.GetString ("_Quit");
			w144.UseUnderline = true;
			w141.Add (w144);
			w140.Add (w141);
			this.btnQuit.Add (w140);
			this.hbtnWindowBox.Add (this.btnQuit);
			global::Gtk.ButtonBox.ButtonBoxChild w148 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnWindowBox [this.btnQuit]));
			w148.Expand = false;
			w148.Fill = false;
			this.vbox2.Add (this.hbtnWindowBox);
			global::Gtk.Box.BoxChild w149 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbtnWindowBox]));
			w149.PackType = ((global::Gtk.PackType)(1));
			w149.Position = 8;
			w149.Expand = false;
			w149.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1022;
			this.DefaultHeight = 555;
			this.aliTop.Hide ();
			this.aliBetweenbtnDatabtnMove.Hide ();
			this.aliBetweenlblArtistPathtxtPath.Hide ();
			this.aliBetweenlblAlbumtxtAlbum.Hide ();
			this.aliBetweenlblSongPathtxtSongPath.Hide ();
			this.Show ();
			this.btnEditTag.Clicked += new global::System.EventHandler (this.EditTagInformationButton);
			this.btnEditCancel.Clicked += new global::System.EventHandler (this.CancelTagOperationButton);
			this.btnEditUpdate.Clicked += new global::System.EventHandler (this.UpdateTagFileButton);
			this.btnEditOpen.Clicked += new global::System.EventHandler (this.OpenSongFileButton);
			this.btnFirst.Clicked += new global::System.EventHandler (this.MoveToFirstTagRecordButton);
			this.btnPrevious.Clicked += new global::System.EventHandler (this.MoveToPreviousTagRecordButton);
			this.btnNext.Clicked += new global::System.EventHandler (this.MoveToNextTagRecordButton);
			this.btnLast.Clicked += new global::System.EventHandler (this.MoveToLastTagRecordButton);
			this.btnLoadTags.Clicked += new global::System.EventHandler (this.LoadAllSongTagsButton);
			this.btnErrorTags.Clicked += new global::System.EventHandler (this.ShowSongTagsWithErrorsButton);
			this.btnValidTags.Clicked += new global::System.EventHandler (this.ShowValidSongTagsButton);
			this.btnQuit.Clicked += new global::System.EventHandler (this.QuitSongTagWindowButton);
		}
	}
}
