
// This file has been generated by the GUI designer. Do not modify.
namespace MusicManager
{
	public partial class MessageWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MusicManager.MessageWindow
			this.Name = "MusicManager.MessageWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MessageWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Hide ();
		}
	}
}
