
// This file has been generated by the GUI designer. Do not modify.
namespace MusicManager
{
	public partial class MyInputDialog
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label lblInfo;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.Entry txtData;
		private global::Gtk.Button btnCancel;
		private global::Gtk.Button btnOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MusicManager.MyInputDialog
			this.WidthRequest = 600;
			this.Name = "MusicManager.MyInputDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Message Input Box");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			// Internal child MusicManager.MyInputDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblInfo = new global::Gtk.Label ();
			this.lblInfo.WidthRequest = 0;
			this.lblInfo.HeightRequest = 60;
			this.lblInfo.Name = "lblInfo";
			this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.lblInfo.Wrap = true;
			this.lblInfo.Justify = ((global::Gtk.Justification)(2));
			this.vbox3.Add (this.lblInfo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblInfo]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.HeightRequest = 30;
			this.alignment2.Name = "alignment2";
			this.vbox3.Add (this.alignment2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment2]));
			w3.Position = 1;
			w3.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.txtData = new global::Gtk.Entry ();
			this.txtData.CanFocus = true;
			this.txtData.Name = "txtData";
			this.txtData.IsEditable = true;
			this.txtData.InvisibleChar = '•';
			this.vbox3.Add (this.txtData);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.txtData]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			w1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox3]));
			w5.Position = 0;
			// Internal child MusicManager.MyInputDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.HeightRequest = 60;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.CanDefault = true;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseStock = true;
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.btnCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.btnCancel]));
			w7.Expand = false;
			w7.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnOk = new global::Gtk.Button ();
			this.btnOk.CanDefault = true;
			this.btnOk.CanFocus = true;
			this.btnOk.Name = "btnOk";
			this.btnOk.UseStock = true;
			this.btnOk.UseUnderline = true;
			this.btnOk.Label = "gtk-ok";
			this.AddActionWidget (this.btnOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.btnOk]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 602;
			this.DefaultHeight = 237;
			this.Show ();
			this.btnCancel.Clicked += new global::System.EventHandler (this.SelectedCancelButton);
			this.btnOk.Clicked += new global::System.EventHandler (this.SelectedOkButton);
		}
	}
}
